### ISSUE TITLE
Segment not sent when request is aborted

### ISSUE THREAD

**Issue by crystalin** [aws/aws-xray-sdk-node#104]
The openSegment function relies on `res.on('finish', function () {` to send the segment to the deamon.
However if the request is aborted (because the client timesout for example), the "finish" event is not sent (the "close" event is sent instead it seems)

A solution similar to https://github.com/jshttp/on-finished would be more reliable

**Comment by chrisradek** [comment]
@crystalin 
Thank you for opening this issue, that's a good find! Will mark this as a bug, I agree we need to handle the aborted request scenario.
