### ISSUE TITLE
Failed to get the current sub/segment when writing unit tests

### ISSUE THREAD

**Issue by manchuck** [aws/aws-xray-sdk-node#110]
I'm trying to write a unit tests for a function which is traced. I've been stuck trying to bootstrap the test. 

``src/mysql.js``:
```javascript
module.exports.executeMysqlQuery = async (pool, sql, params = []) => {
    return new Promise(async (resolve, reject) => {
        xray.captureAsyncFunc('mysql-query', async (subsegment) => {
            subsegment.addAnnotation('query', sql);
            try {
                const results = await pool.execute(sql, params);
                subsegment.close();
                resolve(results);
            } catch (error) {
                reject(error);
                subsegment.close(error);
            }
        });
    });
};
```
``tests/mysqlTest.js``
```javascript
const {expect} = require('chai');
const mysql = require('mysql2');
const {executeMysqlQuery} = require('../src/mysql');
const xray = require('aws-xray-sdk');


describe('mysql', () => {
    const sandbox = require('sinon').createSandbox();
    const namespace = xray.getNamespace();
    const segment = new xray.Segment('root');

    beforeEach(async () => {
        return await namespace.run(() => {
            xray.setSegment(segment);
        });
    });

    afterEach(() => {
        sandbox.verify();
        sandbox.restore();
        segment.close();
    });

    context('executeMysqlQuery', () => {
        it('Should Execute Query', async () => {
            const name = 'manchuck';
            const fields = ['id', 'name'];
            const expected = [{id: 0, name: name}];
            const results = [expected, fields];
            const pool = mysql.createPool({host: 'localhost'});

            const poolMock = sandbox.mock(pool);
            poolMock.
                expects('execute').
                once().
                withArgs('select * from users where name = ?', [name]).
                resolves(results);

            const actualResults = await executeMysqlQuery(
                pool,
                'select * from users where name = ?',
                [name],
            );

            expect(actualResults).deep.eq(expected);
        });
    });
});
```

When executing the test, I'm getting ``Error: Failed to get the current sub/segment from the context.``.

**Comment by bluehawk27** [comment]
I'm running into this as well when running jest in an automated unit test run with codebuild.

**Comment by chrisradek** [comment]
@manchuck 
Are you using the `experimental` version of the SDK? That version supports async/await.

You can install it using: `npm install --save aws-xray-sdk@experimental`

**Comment by manchuck** [comment]
@chrisradek Yes I am using ``2.1.0-experimental.1``

**Comment by ghingis** [comment]
I had the same issue, but I'm testing with `jest`.
For the workaround I just mocked the `captureAsyncFunc`.
```js
xray.captureAsyncFunc = jest.fn((name, fn) => {
    fn({
        addAnnotation: () => {},
        close: () => {},
        // ... add whatever you use on the subsegment
    });
});
```
Maybe with `chai-spies` you could do something similar.

**Comment by yvele** [comment]
Same problem here, I'm also using a jest mockup like that:

```js
import xray from "aws-xray-sdk-core";

jest.spyOn(xray, "captureFunc").mockImplementation((name, fn) => fn());

describe("test", () => {
   ...
});
```

**Comment by Gerst20051** [comment]
I decided to keep X-Ray disabled for unit tests. Like this:

```
if (!process.env.IS_OFFLINE) {
  AWSXRay.captureHTTPsGlobal(require('http'));
}
```

**Comment by hauboldj** [comment]
It would be fantastic if the xray sdk had a global option for disabling during unit testing.

**Comment by manchuck** [comment]
Because of this issue I gave up on using XRay. All our services are following CI/CD and if I can't test them, they can't deploy.  I hope that this issue can get resolved.

**Comment by willarmiros** [comment]
Hi @manchuck,
Sorry for the delayed response, and I apologize for the frustration you're experiencing. While it does not strictly disable X-Ray, you may prevent the errors you are receiving from failing your unit tests using the `ContextMissingStrategy`. This can be done by setting the `AWS_XRAY_CONTEXT_MISSING` environment variable to `LOG_ERROR`. This emits a warning to the logs when the SDK encounters the error you're receiving rather than causing a runtime error. Read more about our environment variables [here](https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#environment-variables) (but please note the log level setting feature has not been released to NPM yet).

Additionally, you can set a custom context missing strategy with a function of your own (e.g. a no-op) using [this API](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/context_utils.js#L157). Sorry for the lack of formal documentation, please reach out again if you need further clarifications. It should be noted that setting the context missing environment variable will override any custom function provided programmatically.

**Comment by manchuck** [comment]
@willarmiros I will close the issue once the documentation has been updated.

**Comment by willarmiros** [comment]
Hi @manchuck,
You can view the updated documentation [here](https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#context-missing-strategy-configuration). Hope this resolves your issue!

**Comment by manchuck** [comment]
@willarmiros Ahh so good.  Closing this issue

**Comment by vanhumbeecka** [comment]
@willarmiros setting the `AWS_XRAY_CONTEXT_MISSING` does NOT seem to work when using "manual mode" for x-ray... 
Even though the env is set, running unit tests dumps the `ContextMissingStragetegy` errors in the console
