### ISSUE TITLE
Unsafe access on cls.getNameSpace()

### ISSUE THREAD

**Issue by samhuk** [aws/aws-xray-sdk-node#111]
In lib/context_utils.js, unsafe access in `setSegment: Function`:

```js
cls.getNamespace(NAMESPACE).set(SEGMENT, segment)
```

**Comment by chrisradek** [comment]
@samhuk 
It looks like this was edited a few times. Can you share more details on what steps to take to encounter an issue? Are you getting an error, or seeing unexpected behavior?

**Comment by samhuk** [comment]
Ah yes of course. My initial issue was with another different npm package that used cls-hooked (correlation-id). It turns out that other packages that later initialise this local storage feature will overwrite the storage and cause this line to throw a fatal exception.

**Comment by chrisradek** [comment]
Are you using the `experimental` branch of the SDK which depends on `cls-hooked` then? Or the stable version (which is what you'd get if you didn't specify a tag when npm installing) that depends on `continuation-local-storage`?

**Comment by samhuk** [comment]
Sorry for not clarifying. Both of the packages interact with the same storage. What originally motivated me creating the issue was that if one does an `import ... from aws-xray-sdk-node` and next line `import ... from {a-cls-package}`, the initialisation of a-cls-package could wipe the namespace from the storage, and then the unsafe access causes an error instead of gracefully failing ot reinitialisation ("recovering") the state.

**Comment by chrisradek** [comment]
@samhuk 
Thanks for reporting this. I see now that the issue has something to do with `continuation-local-storage` and `cls-hooked` being imported in the same project. One overwrites the other.

It looks like we may have to update our code to create the namespace if it doesn't exist. If you switch to the `experimental` tag of the SDK (npm install --save aws-xray-sdk@experimental) does this issue go away?

**Comment by samhuk** [comment]
Only just looking at this now. Good work, can confirm it works with other cls package.
