### ISSUE TITLE
Sql query subsegments are not shown in AWS X-ray management console

### ISSUE THREAD

**Issue by nilkrdg** [aws/aws-xray-sdk-node#112]
I am working on a REST API which is running on a Lambda function with Node 8.10 version. The requests to lambda function comes from the AWS API Gateway service. I have added 
open/close segment calls before and after routes settings in my App class with aws-xray-sdk version 2.2.0.

```js
    this.app.use(AWSXRay.express.openSegment("my_server"));
    this.routes.routes(this.app);
    this.app.use(AWSXRay.express.closeSegment());`
```

I have used the aws-xray-sdk-core version 2.2.0 to call captureAsyncFunc. I couldn't use aws-xray-sdk-postgres because I am using PoolClient instead of Client for postgres and aws-xray-sdk-postgres is expecting postgres Client object. So I had to use custom capture function. 

**This is the async/await function that I call captureAsyncFunc:**

```js
  export async function timeSegment<T>(
  name: string,
  callback: () => T
): Promise<T> {
  if (Environment.isTesting) {
    return callback();
  }
  return new Promise<T>((resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => {
    AWSXRay.captureAsyncFunc(name, async (subSegment: AWSXRay.subsegment) => {
      try {
        const result: T = callback();
        subSegment.close();
        resolve(result);
      } catch (error) {
        subSegment.close();
        reject(error);
      }
    });
  });
}
```

**This is how I call it for sql queries:**

```js
const result = await timeSegment("getItems", async () =>  db.query(getItemsQuery, [clientId]));
```

**Comment by chrisradek** [comment]
@nilkrdg 
If you invoke your lambda function a couple times, do you start to see SQL query subsegments?

If your Lambda function returns a promise, or is using async/await, can you try updating it so that the last line of your handler passes the return value (assuming resolved promise) to the callback function that's an argument to your handler?

**Comment by okonon** [comment]
@nilkrdg did you have a chance to do the above?

**Comment by muriloao** [comment]
This issue has been solved ? I have the same case

**Comment by willarmiros** [comment]
Hi @muriloao,
Did you try what @chrisradek suggested? There are some known weird behaviors with Lambdas and async/await functions that sometimes cause subsegments closed in `async` functions to not be reflected on the console. See #219 and #222. 

That being said, can you elaborate on your use case a little more so I can compare it with @nilkrdg?
