### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by keroic** [aws/aws-xray-sdk-node#121]
I am trying to use 2.3.1 Release to use MySQL Pool getConnection function, but seems it throw the error and exit my application.

TypeError: Cannot read property 'then' of undefined
Pool.patchedGetConnection [as getConnection] (/usr/src/app/node_modules/aws-xray-sdk-mysql/lib/mysql_p.js:111:16)
at Promise

Anything I missed to config? :-(

**Comment by chrisradek** [comment]
@keroic 
This looks related to #120 
We merged that in yesterday, I'll cut a release today that includes this change.
