### ISSUE TITLE
release notes

### ISSUE THREAD

**Issue by jboehle** [aws/aws-xray-sdk-node#127]
I see there have been several releases recently. Are there release notes somewhere so we can know what's changed?

**Comment by chrisradek** [comment]
@jboehle 
The starting place to see release notes would be the `full_sdk` package [CHANGELOG.md](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/full_sdk/CHANGELOG.md)

We should add a link to this from our main README as well to help with discoverability.

**Comment by awssandra** [comment]
Added link in readme: https://github.com/aws/aws-xray-sdk-node/commit/ad817e5ccfbb803ec4140cd8a457be579ea3cc1c
