### ISSUE TITLE
Difference with using aws-sdk directly?

### ISSUE THREAD

**Issue by ChenLi0830** [aws/aws-xray-sdk-node#138]
Hi there, what is the difference between this package and using the aws-sdk/clients/xray directly?

https://github.com/aws/aws-sdk-js/blob/master/clients/xray.d.ts

**Comment by awssandra** [comment]
Hi ChenLi0830,

X-Ray is built with the idea that every component of your distributed service emits a segment which is constructed into a trace by the X-Ray service. A trace represents a single transaction (for example, a single GET request to your web front-end) and the resultant chain of calls that propagate through the service, with each component collecting and transmitting their own data, as well as propagating the trace header.

The X-Ray SDKs collect and format the data into our [trace segment format](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html). The SDK provides easy hooks to allow the data collection to be as non-intrustive as possible. The SDK also automatically propagates the [tracing header](https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader) on downstream calls over HTTP and through the AWS SDK (via patchers). When a segment is closed, it's automatically flushed over UDP to be picked up by the X-Ray daemon.

The X-Ray daemon is in charge of auto, batching, buffering and retrying sending the segments to the X-Ray service. This was to offload any additional overhead to a sidecar process.

The AWS SDK merely provides a client to call to the X-Ray APIs directly. You'd don't need to use the X-Ray SDKs or the daemon, but it makes it easier to construct the data in the format the APIs expect.

Hopefully this clears up any questions.

Thanks!
Sandra

**Comment by ChenLi0830** [comment]
@awssandra Thank you for the detailed answer Sandra! Closing the issue.
