### ISSUE TITLE
_X_AMZN_TRACE_ID is missing required data.

### ISSUE THREAD

**Issue by AndreaAdvanon** [aws/aws-xray-sdk-node#139]
I have a serverless project where I'm using 2 different services I'd like to use with xray:
- ssm
- rds (postgres)

As soon as I run this code:
```javascript
const AWSXRay = require('aws-xray-sdk');
const AWS = AWSXRay.captureAWS(require('aws-sdk'));
```

I get these logs:
```
_X_AMZN_TRACE_ID is missing required data.
_X_AMZN_TRACE_ID is missing required data.
_X_AMZN_TRACE_ID is missing required data.
_X_AMZN_TRACE_ID is missing required data.
START RequestId: aaaaaa Version: $LATEST
```

And I do not see traces for ssm calls.
I do see RDS traces later in the execution.

The `captureAWS` and `ssm` calls happens during the initialization of the container (I think), since they run in a [middy](https://github.com/middyjs/middy) middleware.

**Comment by awssandra** [comment]
Hi AndreaAdvanon,

Sorry for the issues. The _X_AMZN_TRACE_ID is not available outside the function handler (a known shortcoming of the current Lambda/X-Ray integration). We're planning to work with the Lambda team to better define a more complete X-Ray experience.

Documentation: https://docs.aws.amazon.com/lambda/latest/dg/downstream-tracing.html

**Comment by AndreaAdvanon** [comment]
thanks for your answer @awssandra, is it safe to ignore these logs?

**Comment by awssandra** [comment]
Hi AndreaAdvanon,

They serve as a notification that tracing could not be initiated, but no harm will come from them. However, you can choose to capture specific AWS clients if you would like to avoid the messages (or construct the clients you'd like to opt-out before capturing the AWS SDK). 

Hope this helps,
Sandra
