### ISSUE TITLE
Typescript Definitions

### ISSUE THREAD

**Issue by glicht** [aws/aws-xray-sdk-node#14]
Hi,

Are there anywhere typescript definitions for this project? 
If not, do you have any plans to provide typescript definitions in the future?

thanks,

Guy

**Comment by haotianw465** [comment]
Hi, the SDK currently doesn't have typescript definitions available yet. We will looking into providing the definitions but we cannot guarantee such offering nor a timeline. Please stay tuned.

**Comment by piersmacdonald** [comment]
Lacking Typescript and Node 8+ support isn't great for a non-beta AWS product.

**Comment by NachtmahrEDM** [comment]
I also would love to see typescript definitions soon as our company is dependent on aws and typescript.

**Comment by voxpelli** [comment]
Definitions are getting increasingly common among projects and since Typescript at least nowadays can also be used to lint pure js I think it's a very good suggestion.

However: Anyone can contribute type definitions for this package to the @DefinitelyTyped project: https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

**Comment by alex-at-cascade** [comment]
This would be very nice to have, as it's very frustrating how the `AWSXRay.captureAWS(...)` call obscures the valuable `.d.ts` declarations provided by the AWS sdk.

**Comment by kerbyferris** [comment]
As a workaround, generics can help. Creating a `aws-xray-sdk.d.ts` types file with something like the following will satisfy the compiler without obscuring AWS sdk declarations:

```
declare module "aws-xray-sdk" {
  export function captureAWSClient<T>(client: T): T;
  ...
}
```

**Comment by sergiovm** [comment]
> Definitions are getting increasingly common among projects and since Typescript at least nowadays can also be used to lint pure js I think it's a very good suggestion.
> 
> However: Anyone can contribute type definitions for this package to the @DefinitelyTyped project: https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

Somebody created a basic definition here:
https://github.com/mziyabo-aws/aws-xray-typings

Not perfect though...

**Comment by woodsae** [comment]
I would really like to see this done as well.

**Comment by esilkensen** [comment]
Hi everyone, I've just opened #207  🙂

**Comment by willarmiros** [comment]
TypeScript definitions have been released in v2.5.0!

**Comment by LosD** [comment]
@willarmiros Is it on purpose that the definitions has been added to dependencies instead of dev-dependencies? That seems like a mistake.

**Comment by esilkensen** [comment]
I think it's correct for it to be a dependency, because the `Namespace` type is imported from that package and exported as the return type of the public `getNamespace()` function -- that said, since #227 was merged this should probably be updated to use `@types/cls-hooked` -- I can open a PR for that.

**Comment by LosD** [comment]
@esilkensen Sorry, I moved my question to the PR, probably after you saw it (I've copied it under here, though a little differently worded, as I changed it a bit as I moved it).

Anyway, at runtime, types are gone, and has no purpose anymore? It might be me missing a difference when doing libraries as opposed to applications, but it makes no sense to me to keep types around for runtime.

> @willarmiros @esilkensen Is it on purpose that @types/continuation-local-storage has been added to dependencies instead of dev-dependencies? That seems like a mistake, as it'll make the package larger (right now, that of course drowns in comparison to the aws-sdk, but when that is removed, the typings is the largest dependency by far)
