### ISSUE TITLE
How can I show the error being thrown in XRay console?

### ISSUE THREAD

**Issue by SamVerschueren** [aws/aws-xray-sdk-node#141]
Hi

I'm using XRay with AWS Lambda and was wondering why an error, thrown in my code, doesn't end up in in the `Exceptions` tab inside the `Segment`?

What I do in my Lambda handler is just `throw new Error('Hello world');` but the `Exceptions` tab stays empty.

![image](https://user-images.githubusercontent.com/1913805/58655063-97759f80-8319-11e9-8c1f-ad156486b9ad.png)

The overview shows that something went wrong, but this doesn't allow me to easily pinpoint the error and on which line (stack trace).

![image](https://user-images.githubusercontent.com/1913805/58655113-b2481400-8319-11e9-9b2e-0a030e33913a.png)

Am I doing something wrong? Do I need to take manual action to add the stack trace to my segment?

Kind regards,
Sam

**Comment by awssandra** [comment]
Hi SamVerschueren,

Sorry for the late reply.
Can you post your raw trace data? I want to see if the stack trace/error is on the segment at all.

**Comment by kevin-miles** [comment]
Not a solution, but as a workaround to the issue I have been placing logic within a try/catch block and bubbling the errors up to it.
Inside the catch you can add a subsegment.
In the subsegment, run a `subsegment.addError(err)`

https://docs.aws.amazon.com/xray-sdk-for-nodejs/latest/reference/Subsegment.html

Then when you observe Xray traces you can see quick error output/a nice red error icon next to the subsegment.

**Comment by SamVerschueren** [comment]
@awssandra The error is not in the raw data

```json
{
    "Duration": 3.096,
    "Id": "1-5da015d5-360ce338611f0b7ce8b61474",
    "Segments": [
        {
            "Document": {
                "id": "29fe1e5dc4f44858",
                "name": "test-xray-error",
                "start_time": 1570772437.529,
                "end_time": 1570772440.625,
                "error": true,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "request_id": "c86f641e-0cb9-4744-957a-5dd50e7a6d3a"
                },
                "trace_id": "1-5da015d5-360ce338611f0b7ce8b61474",
                "origin": "AWS::Lambda",
                "resource_arn": "arn:aws:lambda:eu-west-1:333477131547:function:test-xray-error"
            },
            "Id": "29fe1e5dc4f44858"
        },
        {
            "Document": {
                "id": "1976f2c1163c43c5",
                "name": "test-xray-error",
                "start_time": 1570772438.284575,
                "end_time": 1570772440.5232158,
                "parent_id": "29fe1e5dc4f44858",
                "error": true,
                "aws": {
                    "function_arn": "arn:aws:lambda:eu-west-1:333477131547:function:test-xray-error",
                    "resource_names": [
                        "test-xray-error"
                    ],
                    "account_id": "333477131547"
                },
                "trace_id": "1-5da015d5-360ce338611f0b7ce8b61474",
                "origin": "AWS::Lambda::Function",
                "subsegments": [
                    {
                        "id": "1b329401178061a7",
                        "name": "Initialization",
                        "start_time": 1570772438.2847211,
                        "end_time": 1570772440.5230796,
                        "error": true,
                        "aws": {
                            "function_arn": "arn:aws:lambda:eu-west-1:333477131547:function:test-xray-error"
                        }
                    }
                ]
            },
            "Id": "1976f2c1163c43c5"
        }
    ]
}
```

@kevin-miles I'm going to look into that! Thanks for the tip.

**Comment by SamVerschueren** [comment]
I wanted to see what I can do with the `addError`. It seems I can't use `AWSXRay.getSegment().addError()`. Not sure why though, but I had to make a sub segment.

```ts
const AWSXRay = require('aws-xray-sdk-core');

exports.handler = async (event) => {
    AWSXRay.captureFunc('exceptions', subsegment => {
        subsegment.addError(new Error('hello world'));
    });
    
    throw new Error('Something went wrong');
};
```

This attaches the `hello world` error to the segment, but as a sub segment

![image](https://user-images.githubusercontent.com/1913805/66628685-d2f57400-ebff-11e9-9d8c-2c17093abb1b.png)

Can't I just add it to my `Invocation` or to my `test-xray-error` parent node?

I also wanted to add a global error handler like this

```ts
const AWSXRay = require('aws-xray-sdk-core');

process.on('uncaughtException', error => {
    console.log(error);
    
    AWSXRay.captureFunc('annotations', subsegment => {
        subsegment.addError(error);
    });
});

exports.handler = async (event) => {
    throw new Error('Something went wrong');
};
```

The error is printed, but it's not added to the sub segment.

So in general, yes it can be done manually through `addError` but it feels cumbersome. Can't this be done automatically in the XRay SDK itself? If not, can I do it in the `uncaughtException` handler?

**Comment by SamVerschueren** [comment]
I think I was wrong regarding the `uncaughtException`. That handler is actually never executed. Probably because Lambda catches the errors in the background automatically which makes that errors or always caught.

**Comment by willarmiros** [comment]
Hi @SamVerschueren,
You cannot use `addError()` on the segment in a Lambda function because the segment created by the Lambda service is immutable by customer code. That and the `initialization`, `invocation`, and `overhead` subsegments are only used internally and will perform no-ops on all methods applied to them. Creating and operating with custom subsegments is the correct approach. 

Either surrounding your handler code with a try/catch block and manually creating a subsegment and adding the error as @kevin-miles suggested. By the way, the `close()` method implicitly calls addError and handles cleanup work for the subsegment:
```
var AWSXRay = require('aws-xray-sdk');

exports.handler = async (event) => {
    var sub = AWSXRay.getSegment().addNewSubsegment('testError');
    try {
        // Some code...

        throw new Error('Something went wrong.');
    } catch (e) {
        sub.close(e, false); // Or sub.addError()
    }
};
```
Or you can surround your code with the `captureFunc()` or `captureAsyncFunc()` API to capture exceptions in your handler automatically:

```
var AWSXRay = require('aws-xray-sdk');

exports.handler = async (event) => {
    AWSXRay.captureFunc('testError', subsegment => {
        // Some code...
        
        throw new Error('Something went wrong');
    });
};
```

Please let me know if you have further questions, otherwise I'll close this issue.
