### ISSUE TITLE
Jest tests locking up

### ISSUE THREAD

**Issue by duro** [aws/aws-xray-sdk-node#142]
I am writing some unit tests around some code that is including the xray-sdk, and I am getting some errors with my jest tests:

```
Jest did not exit one second after the test run has completed.
```

When I run my tests with `--detectOpenHandles` I get the following back:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  UDPWRAP

      at Object.<anonymous> (../../node_modules/aws-xray-sdk-core/lib/segment_emitter.js:105:17)
      at Object.<anonymous> (../../node_modules/aws-xray-sdk-core/lib/segments/segment.js:12:22)
```

I have tried to add conditionals in my code that pretty much disable xray when we are in a jest environment, but I still keep getting these errors.

**Comment by duro** [comment]
I got to the bottom of this, and it turns out it was something completely unrelated that was hanging Jest, but for some reason the `--detectOpenHandles` was calling out `aws-xray-sdk-core` for some odd reason.

**Comment by james-stanley** [comment]
What ended up being the issue? I'm experiencing the same error and am looking for any hints

**Comment by duro** [comment]
@james-stanley something else was causing Jest to not exit after tests. In my case it was a connection to my database. For some reason Jest likes to single out X-Ray when it cannot otherwise figure out what the open handle is.
