### ISSUE TITLE
Lodash Dependency Vulnerability

### ISSUE THREAD

**Issue by adeelejaz-plt** [aws/aws-xray-sdk-node#150]
Versions of lodash lower than 4.17.11 have a security vulnerability (https://tools.cisco.com/security/center/viewAlert.x?alertId=59546).

AWS SDK have done a release with the fix, so we should do an upgrade to latest version of AWS SDK and bump the lodash to latest patched version.

**Comment by awssandra** [comment]
Hi adeelejaz-plt,

The X-Ray SDK already uses 4.17.11 of lodash, so it is not impacted directly. The AWS SDK does not pull this in either. It appears a few of our developer dependencies may be pulling in the lower version though. We are auditing the remaining packages.

**Comment by awssandra** [comment]
Hi adeelejaz-plt,

Just to confirm, only one of our development dependencies is affected. We are releasing a fix ASAP.

**Comment by yogiraj07** [comment]
Hi @adeelejaz-plt,
Release V2.3.4 contains this fix.

Thanks,
Yogi
