### ISSUE TITLE
Lambda with Kinesis Trigger Receives Repeat Trace IDs

### ISSUE THREAD

**Issue by timtrinidad** [aws/aws-xray-sdk-node#164]
I'm having trouble debugging one of my lambda functions that is triggered by Kinesis Streams. When I turn on `AWS_XRAY_DEBUG_MODE`, I see the following messages:

```
  | Aug 17 00:35:36.631 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=36fcaefc2fcbbfac;Sampled=1
  | Aug 17 00:34:40.031 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=77d41a854a5e5885;Sampled=1
  | Aug 17 00:33:26.490 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=00eafba04792e923;Sampled=1
  | Aug 17 00:32:15.949 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=410200115c44c77f;Sampled=1
  | Aug 17 00:31:07.891 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=013133ae29c1139f;Sampled=1
  | Aug 17 00:29:53.791 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=5e420c7b6a462035;Sampled=1
  | Aug 17 00:29:01.250 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=2d33dd3c5ba3cf07;Sampled=1
  | Aug 17 00:28:00.468 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=6e6752837f4147df;Sampled=1
  | Aug 17 00:27:03.770 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=5ede6c446dd2f391;Sampled=1
  | Aug 17 00:26:03.650 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=6b68f42779dcae3d;Sampled=1
  | Aug 17 00:25:11.229 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=465b2496602d3096;Sampled=1
  | Aug 17 00:24:16.412 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=455b2e0748ef746e;Sampled=1
  | Aug 17 00:23:23.530 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=4a0239722ddbc10f;Sampled=1
  | Aug 17 00:22:35.890 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=25089ba561e66e5a;Sampled=1
  | Aug 17 00:21:29.912 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=1c4d604414749a6b;Sampled=1
  | Aug 17 00:20:42.832 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=4017b340611bcf8a;Sampled=1
  | Aug 17 00:19:51.470 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=198ea40d4b56bd8d;Sampled=1
  | Aug 17 00:19:00.350 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=21eb645a0b0c4a8d;Sampled=1
  | Aug 17 00:17:48.511 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=2ba582710bc31ecb;Sampled=1
  | Aug 17 00:16:51.591 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=5c32fb007f23d1a7;Sampled=1
  | Aug 17 00:16:10.489 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=4291229c1beb5949;Sampled=1
  | Aug 17 00:15:46.588 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=46668b2d646466f5;Sampled=1
  | Aug 17 00:15:30.410 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=0d33c47130037e62;Sampled=1
  | Aug 17 00:15:23.410 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=4c7d12697cee3700;Sampled=1
  | Aug 17 00:15:20.589 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=6bb38d66128f4ec7;Sampled=1
  | Aug 17 00:15:18.830 | Lambda trace data found: Root=1-5d574711-0eeb9d8a0e9daa91af40f017;Parent=1ccf9bd22b7f416d;Sampled=1
```

You'll see that different invocations at different times have the same trace ID. How do I make sure that each invocation has a different trace ID?

**Comment by willarmiros** [comment]
Hello,
We're happy to take a look at this, but we'll need some clarification. Can we see a screenshot what this trace looks like? The X-Ray SDK does not currently support instrumentation of Kinesis Streams, but have you instrumented the Kinesis Streams with X-Ray in any sort of custom fashion? Have you enabled X-Ray active tracing on the Lambda dashboard? What runtime is your function using?

Thanks!

**Comment by timtrinidad** [comment]
To clarify - this is instrumentation of a lambda function, not of the kinesis stream itself.

Here's a screenshot of the trace. As you can see, the trace goes on for 8+ minutes even though lambda has a max runtime of 5mins. Let me know if this is a ticket that should be filed with the lambda or kinesis streams teams.

![screencapture-console-aws-amazon-xray-home-2019-08-23-16_24_02](https://user-images.githubusercontent.com/2067202/63628703-c4f18280-c5c2-11e9-83ec-6b9dc81ff219.png)

**Comment by willarmiros** [comment]
Thanks for the information. We're looking into this and will follow up again once we know more about your issue.

**Comment by willarmiros** [comment]
Thank you for your patience. You are correct that this is not the expected behavior when invoking an instrumented Lambda function. We are actively working with the Lambda team to investigate this issue, and will post any updates to this thread.

**Comment by willarmiros** [comment]
@timtrinidad could you email the following information to armiros@amazon.com:
1. Your function ARN
2. Your stream ARN
3. Your event source mapping UUID (retrieved by calling getEventSourceMapping)
4. Request ids WITH timestamps (request ids without timestamps seldom have use)
5. A snippet of your Lambda code to reproduce the issue

**Comment by timtrinidad** [comment]
Recent traces appear to be split out properly - not sure if the Kinesis team release a fix recently. I'll close this out for now and reopen if I see the issue pop up again.
