### ISSUE TITLE
AWS_XRAY_CONTEXT_MISSING is set. Configured context missing strategy to LOG_ERROR

### ISSUE THREAD

**Issue by cheesiangcs** [aws/aws-xray-sdk-node#175]
I realised that there are few lines of X-Ray message printed in my Cloudwatch log after newly released for "aws-xray-sdk-node" a few days ago. 

May I understand is there any configuration error at my end that caused these X-Ray message showing up? or should I ignore this message?

```
09:48:08 2019-09-04T01:48:08.251Z	ckmvv8vkr9153ccd	START-LAMBDA 2019-09-04T01:48:08.250Z
09:48:08 Starting the AWS X-Ray SDK in automatic m
![CloudWatch_Management_Console-2](https://user-images.githubusercontent.com/35026330/64221193-8d59d300-cefe-11e9-9ce9-fa0213339e6d.png)
ode (default).
09:48:08 AWS_XRAY_CONTEXT_MISSING is set. Configured context missing strategy to LOG_ERROR.
09:48:09 Subsegment streaming threshold set to: 0
09:48:09 Starting the AWS X-Ray SDK in automatic mode (default).
09:48:09 AWS_XRAY_CONTEXT_MISSING is set. Configured context missing strategy to LOG_ERROR.
09:48:09 Subsegment streaming threshold set to: 0
09:53:18 START RequestId: b371cc60-8f38-4b11-92a3-eadb2a2043ed Version: $LATEST
...
```

![CloudWatch_Management_Console-2](https://user-images.githubusercontent.com/35026330/64221212-9f3b7600-cefe-11e9-8018-919b949e1e08.png)

**Comment by willarmiros** [comment]
Hi @cheesiangcs,
Thanks for bringing this to our attention. It has been addressed in release 2.3.6. Once you have updated to that version, debug messages should only be logged if you have the AWS_XRAY_DEBUG_MODE environment variable set.
