### ISSUE TITLE
S3.upload is not traced.

### ISSUE THREAD

**Issue by hauboldj** [aws/aws-xray-sdk-node#184]
I'm capturing the S3 client as documented.
```
const AWS = require('aws-sdk');
const XRay = require('aws-xray-sdk');
const S3 = XRay.captureAWSClient(new AWS.S3());
```
However the managed upload call S3.upload is not traced.
Other S3 api calls are traced as expected but there is no information for S3.upload. At minimum I expected to see the individual api calls for the managed s3 multipart upload to be traced.

**Comment by willarmiros** [comment]
I understand what you were saying now, sorry for not picking it up earlier. We will open a ticket with the S3 team to discuss this issue and decide how best to move forward. Thanks for bringing this up.

**Comment by willarmiros** [comment]
Hi @hauboldj,
The AWS SDK team informed me `s3.upload` is not an external API intended for use by customers. Is there any reason you are not using `s3.putObject` instead? It is [documented](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) whereas upload is not.

**Comment by hauboldj** [comment]
It is indeed documented. See screenshot and link 
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property

![image](https://user-images.githubusercontent.com/2679742/69471200-c4f05280-0d6a-11ea-903d-e15f976ccf15.png)

The problem is the s3.upload creates a new s3 service object so I have to capture the entire AWS SDK, this worked in my case because it was ok to instrument all API calls across all AWS services.

Capturing the entire AWS SDK does result in the individual `createMultipartUpload` and `uploadPart` being traced, but if you just capture the s3 service the individual api calls are not traced.

**Comment by willarmiros** [comment]
It turns out this issue is the same as #224. `s3.upload` is a public-facing API, and it is documented, but unlike `s3.putObject`, it is not an official client object, which is why the unorthodox internal client creation is done in this case but not for any other client methods. I encourage you to follow up with the [AWS SDK](https://github.com/aws/aws-sdk-js/issues/new/choose) team to find out more about this decision and the appropriate workaround for your use case. Keep an eye on #224 to see if they open an issue instead.

**Comment by hauboldj** [comment]
The `getSignedUrl` doesn't make any HTTP/API calls to AWS, so there wouldn't really be anything to capture.
`s3.upload` makes at least one, perhaps multiple API call so it should have capture results.
This is really probably an issue with the SDK. I'll probably open an issue over there. I'm fine if this is closed , since it doesn't seem reasonable for the xray sdk to have to deal with things that are strangely implemented in the main SDK.
