### ISSUE TITLE
Promise support for Postgres

### ISSUE THREAD

**Issue by charsleysa** [aws/aws-xray-sdk-node#19]
Using promises instead of callbacks fail.

Probably related to #12

**Comment by haotianw465** [comment]
Hi, the SDK does have issues with native promise due to how CLS works. This #11 PR addresses the known issues for now. We are preparing a release and will get the fix out soon.

But we want to make sure this fix also applies to your issue. What error message or stack trace did you see in your case?

**Comment by charsleysa** [comment]
The error comes from this [line](https://github.com/aws/aws-xray-sdk-node/blob/f093d8a4e3c02843410a9699904fc15f776f7baf/packages/postgres/lib/postgres_p.js#L67)  and says there is no `on` function, that is because the code doesn't handle the case where the `query` function returns a promise.

This means that PR #11 will probably not fix this issue.

**Comment by haotianw465** [comment]
You are right. PR #11 only fixes how subsegments captured within promises are structured. The SDK was developed before native Promise came out so it doesn't handle Promise return type. This needs to be fixed. 

We will look into the fix. You are welcome to submit a PR. Since #11 was already merged in, the core functionality works correctly.

**Comment by shaunc** [comment]
Is there a work-around for this case for the moment (using `await client.query()` without a callback?)

**Comment by haotianw465** [comment]
We have not tested the workaround you mentioned yet. Theoretically you will lose the query subsegment as `CLS` doesn't track context on `async/await`. We need to thoroughly test the promise usage around Postgres so we can confidently say the SDK Postgres works with Promise.

**Comment by ngervasi** [comment]
Any news on this?

**Comment by charsleysa** [comment]
Related #60

**Comment by jafl** [comment]
I created #64 to address this.

**Comment by haotianw465** [comment]
This is released as part of `v2.1.0`. Please let me know if you have any questions.
