### ISSUE TITLE
Error: No sub/segment specified in `ManualMode`

### ISSUE THREAD

**Issue by rpgeeganage** [aws/aws-xray-sdk-node#214]
Hi Everyone,
I have the following lambda function.
```ts
import * as xray from 'aws-xray-sdk';

import * as http from 'http';
import * as https from 'https';

// This is my business logic
import {handler} from './handler';

xray.enableManualMode();
xray.capturePromise();

export async function myLambda(
  event: {
        traceId: string, // from another service
        parentSegmentId: string// segment id of the service which generate this event
},
  context: Context
) {
  const parentSegment = new xray.Segment(context.functionName, event.traceId, event.parentSegmentId);
  xray.setSegment(parentSegment);
  parentSegment.addMetadata('event', event);

  xray.captureHTTPsGlobal(http);
  xray.captureHTTPsGlobal(https);

  try {
    await handler(event);
    parentSegment.close();
  } catch (err) {
    parentSegment.addError(error);
    parentSegment.close();

    throw err;
  }
}
```

When I call my lambda function via SQS, I get the below-mentioned error.
```
Error: No sub/segment specified. A sub/segment must be provided for manual mode.
   at Object.contextMissingLogError [as contextMissing] (/var/task/webpack:/home/ct/node_modules/aws-xray-sdk-core/lib/context_utils.js:26:1)
   at Object.resolveSegment (/var/task/webpack:/home/ct/node_modules/aws-xray-sdk-core/lib/context_utils.js:77:1)
   at captureOutgoingHTTPs (/var/task/webpack:/home/ct/node_modules/aws-xray-sdk-core/lib/patchers/http_p.js:66:1)
   at Object.captureHTTPsRequest [as request] 
```

I'm currently using `v2.4.0` of `x-ray nodejs sdk`.

Can anyone help me with this?
Thanks a lot

**Comment by willarmiros** [comment]
A couple of observations:
1. Why are you using manual mode? In manual mode you must pass a reference to an X-Ray segment to every request you make (see [these examples](https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#manual-mode-examples)). You can omit `xray.enableManualMode()` and the segment is passed around automatically.
2. You must call `captureHTTPsGlobal` *before* importing the HTTP library. See this [documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-httpclients.html)

**Comment by rpgeeganage** [comment]
Hi @willarmiros ,
thank you for the quick response.
In the event object, I'm passing a trace id and a segment id which generated in a different service. I want o to have a proper service map which reflects my workflow.
(I updated the description)

**Comment by willarmiros** [comment]
Hi @rpgeeganage,
Sorry I missed this earlier, but you also should not be using `setSegment` in manual mode. As the [documentation](https://docs.aws.amazon.com/xray-sdk-for-nodejs/latest/reference/module-context_utils.html) states, it is only for use in Automatic mode.
 
You are getting this error because you are not passing a reference to the segment you created to `captureHTTPsGlobal`, as is required in manual mode. I *strongly* recommend you remove the line enabling manual mode, and proceed in the default automatic mode. Also, please note my second point in my last comment about your use of `captureHTTPsGlobal`.

**Comment by rpgeeganage** [comment]
Hi @willarmiros,
Thank you so much for the answer. I already try with automatic mode.
The main issue was, when I'm using the automatic mode, and set the error, it does not get reflected in my service map or when trying to view the flow of the trace. With manual mode, it works but I couldn't capture the HTTP calls. 😢 

I was able to track the trace id propagation from my services to this lambda execution.
but I want to add errors in case my lambda fails.

**Comment by willarmiros** [comment]
Please see #141 for information about recording errors in Lambda environments. It should work fine with automatic mode, there are just some quirks about adding them to subsegments you have to observe.

**Comment by willarmiros** [comment]
To add some further clarification, that issue mostly describes how you can capture errors by adding them to subsegments. However, the X-Ray SDK will also automatically capture errors and add them to the `AWS::Lambda::Function` segment if the error is returned from your Lambda function. Note that it must be *returned*, not thrown or else the Lambda will just crash without recording it.
