### ISSUE TITLE
Can't get context with captureAWS

### ISSUE THREAD

**Issue by iq-dot** [aws/aws-xray-sdk-node#215]
Hi guys,

I have been having numerous issues with getting context using NodeJS + Express in elasticbeanstalk environment. I am using automatic mode.

I have fixed my express issues by re-writing the `closeSegment` middleware by storing segment in req.segment and using that to forcefully put segment back into the namespace managed by `cls`. I noticed it exists in the beginning and returns no segment and throws error at the closeSegment.

So now that I have fixed express, I have issues now with instrumenting AWS SDK and it's just not easy for me to solve this without going through and modifying each and every single AWS request manually in my code.

I know this seems to be `cls` related and I am not sure if the fix I did was correct and how to resolve this AWS sdk issues. I am using `AWSXRay.captureAWS(require('aws-sdk'))`

I am using nodejs 8

I've been doing a lot of reading on issues and docs and I can't get a resolution on this, would appreciate any help.

**Comment by willarmiros** [comment]
Hi @iq-dot,
What version of the X-Ray SDK for Node are you using? And could we see a snippet of how you're using the X-Ray middleware with your express application? Why do you need to get segments out of the `cls` namespace after closing them? It is somewhat unclear exactly what your issue is from this description.

**Comment by iq-dot** [comment]
Hi @willarmiros 

I am using the latest SDK v2.5, I upgraded yesterday to get the setUser feature, same issue however.

Just to clarify, I am not trying to get the segment from `cls` after closing, express middleware that comes with XRay was throwing the error in the closeSegment middleware because it could not retrieve the segment with the error `Failed to get the current sub/segment from the context`.

The docs says to do something like this which I have done:

```
  server.use(AWSXRay.express.openSegment(`API ${configuration.common.env}`));
  // my routes 
  server.use(AWSXRay.express.closeSegment()); // this throws an error can't find segment
```

I checked that after the `openSegment` in a different middleware, the segment does exist, however by the time closeSegment is executed, the segment does not exist.

So I basically had to do a small "hack" to get around this:

```
  server.use(AWSXRay.express.openSegment(`Roli API ${configuration.common.env}`));
  server.use(awsXRay.checkSegment()); // my middlware that puts the segment in req object

// my middleware that gets the segment from req object and sets it back into CLS 
// then executes the remaining code from the provided closeSegment middleware
  server.use(awsXRay.closeSegment()); 
```

This is the code from my closeSegment hack:

```
function closeSegment(err, req, res, next) {

  const ns = AWSXRay.getNamespace();

  // sometimes the context is lost on a request so we manually re-set it
  if (!ns.get('segment')) {
    ns.run(function () {
      AWSXRay.setSegment(req.segment);
      awsXRayCloseSegment(); // this is the closeSegment code from the provided express middleware, not mine
    });

  } else {
    awsXRayCloseSegment();
  }
...
}
```

**Comment by willarmiros** [comment]
Hi @iq-dot,
I'm not sure if this is your root cause, but each segment represents a single route in your express application. See my code below for two example routes instrumented with X-Ray.
```
const express = require('express');
const AWSXRay = require('aws-xray-sdk');
const XRayExpress = AWSXRay.express;
const app = express();

app.use(XRayExpress.openSegment('root'));

app.get('/', (req, res) => { 
    res.send('Hello World!');
});

app.use(XRayExpress.closeSegment());

app.use(XRayExpress.openSegment('testPage'));

app.get('/test/', (req, res) => {
    res.send('This is a test!');
});

app.use(XRayExpress.closeSegment());
```

If you define multiple routes for a single segment it can cause unexpected behavior.

**Comment by iq-dot** [comment]
Hi @willarmiros 

I think you maybe on to something, I perhaps misunderstood, I assumed the openSegment is at the beginning of ALL your routes and closeSegment at the end ALL routes because I saw a comment saying the closeSegment must the first error handler.

So are you saying that for EACH route we need an open and close segment? We create a router for each of our module routes files so do we need to do this on each out route files:

```js
const express   = require('express');
const routes     = express.Router();

routes.post('/something', functionOne);
routes.get('/something', functionTwo);

server.use(AWSXRay.openSegment('myNamespaceRoutes');
server.use('/api/namespace', routes);
server.use(AWSXRay.express.closeSegment());
```

Then repeat the above code for each of our route files but with a different segment name?

Best,
Iqbal

**Comment by willarmiros** [comment]
Please see my amended comment. I was mistaken and you can have several routes for 1 segment, but there must not be any other middleware uses between your calls to `openSegment` and `closeSegment`. See my example code.

```
const express = require('express');
const AWSXRay = require('aws-xray-sdk');
const XRayExpress = AWSXRay.express;
const app = express();

app.use(someOtherMiddleWare()); // This is OK

app.use(XRayExpress.openSegment('expressPaths'));

app.use(someOtherMiddleware()); // This is not

app.get('/', (req, res) => { 
    res.send('Hello World!');
});

app.use(someOtherMiddleware()); // This is also not OK

app.get('/test/', (req, res) => {
    res.send('This is a test!');
});

app.use(XRayExpress.closeSegment());

**Comment by rohitchawla22** [comment]
I am seeing similar issues in my Typescript API. 
`    }
2019-11-16 22:18:34.539 -05:00 [ERROR] Error: No sub/segment specified. A sub/segment must be provided for manual mode.
    at Object.contextMissingLogError [as contextMissing] (/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:26:19)
    at Object.resolveSegment (/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:77:43)
    at features.constructor.captureAWSRequest [as customRequestHandler] (/app/node_modules/aws-xray-sdk-core/lib/patchers/aws_p.js:66:29)
    at features.constructor.addAllRequestListeners (/app/node_modules/aws-sdk/lib/service.js:279:34)
    at features.constructor.makeRequest (/app/node_modules/aws-sdk/lib/service.js:203:10)
    at features.constructor.svc.(anonymous function) [as getItem] (/app/node_modules/aws-sdk/lib/service.js:673:23)
    at DocumentClient.makeServiceRequest (/app/node_modules/aws-sdk/lib/dynamodb/document_client.js:97:42)
    at DocumentClient.get (/app/node_modules/aws-sdk/lib/dynamodb/document_client.js:263:17)
    at DatabaseClient.get (/app/rocket-db/build/DatabaseClient.js:31:36)
    at`

I have this added at the beginning of my code. 
`const AWSXRay = require('aws-xray-sdk'),
    AWS = AWSXRay.captureAWS(require('aws-sdk'));`
I am trying to implement Xray using Hapi Xray plugin and i am seeing traces locally as well. There problem is that because of this error, I am not able to deploy the API. 
Any suggestions would be appreciated.

**Comment by iq-dot** [comment]
@willarmiros 

Ok so after some testing, I can confirm that it partially fixes the first issue of my normal express routes not finding the segment (which I had hack fixed as well) however this still doesn't fix the AWS SDK throwing the segment error, any routes that use AWS SDK which is wrapped by the AWS XRAY still throws this error, almost as if it is creating it's own separate context using `cls`?

Here is how we use AWS services:

// cloudfront example
```js
const configuration = require('../../configuration'),
      AWSXRay       = require('aws-xray-sdk'),
      AWS           = AWSXRay.captureAWS(require('aws-sdk'));

AWS.config.update({
  region     : configuration.aws.region,
  sslEnabled : true
});

module.exports = new AWS.CloudFront();
```

For S3 we export our own wrapped functions:

```js
const configuration = require('../../configuration'),
      httpStatuses  = require('http-status'),
      AWSXRay       = require('aws-xray-sdk'),
      AWS           = AWSXRay.captureAWS(require('aws-sdk'));

AWS.config.update({
  region     : configuration.aws.region,
  sslEnabled : true
});

const s3 = new AWS.S3();

/*
 * Sign an S3 URL
 */
module.exports.sign = function sign(bucket, key, expirySecs, callback) {
  s3.getSignedUrl('getObject', { Bucket: bucket, Key: key, Expires: expirySecs }, (error, url) => {
    if (error) return callback(error);
    return callback(error, url);
  });
};

module.exports.listObjects = function listObjects(bucket, prefix, callback) {
  return s3.listObjects({ Bucket: bucket, Prefix: prefix }, callback);
};

module.exports.listDirectories = function listObjects(bucket, prefix, callback) {
  return s3.listObjectsV2({ Bucket: bucket, Prefix: prefix, Delimiter: '/' }, callback);
};
```

Is the above style problematic?

**Comment by willarmiros** [comment]
@rohitchawla22 It appears you might have a separate issue since you're using manual mode. Have you checked to make sure you're manually passing around (sub)segment references to all your AWS requests? If not feel free to open a separate issue with more details and a code snippet. 

@iq-dot I was unable to reproduce this issue in my environment. It looks fine and I used the same format for those functions. It is likely an issue of not having a segment available when you're making these S3 calls. Check to see if `AWSXRay.getSegment()` returns a valid reference to a segment in the places you're calling the S3 functions. It it's not, you should open a new segment with the express middleware before making the calls, or just remove instrumentation for the AWS calls.

**Comment by iq-dot** [comment]
@willarmiros Your right setting it just before calling does resolve the issue, however it is a bit unpractical for us with an old established codebase and quite invasive to change them. I guess we just have to not instrument for now and wait for hopefully a better solution then CLS to retrieve current segment.

**Comment by willarmiros** [comment]
As one final suggestion, you can retrieve the namespace with `AWSXRay.getNamespace()`, start a namespace session, construct a segment, and call `AWSXRay.setSegment(segment)` from within the namespace session as a workaround described in the [custom solutions](https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#developing-custom-solutions-using-automatic-mode) section of the docs.
