### ISSUE TITLE
Getting typescript build errors with latest version 2.5.0

### ISSUE THREAD

**Issue by duro** [aws/aws-xray-sdk-node#220]
Upgrading to lastest version of the aws-xray-sdk, my typescript build is now throwing:

```
Type 'PatchedAWSClient<SNS>' is not assignable to type 'SNS'.
  Types of property 'addPermission' are incompatible.
    Type 'PatchedAWSRequestMethod<AddPermissionInput, {}>' is not assignable to type '{ (params: AddPermissionInput, callback?: ((err: AWSError, data: {}) => void) | undefined): Request<{}, AWSError>; (callback?: ((err: AWSError, data: {}) => void) | undefined): Request<...>; }'.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'err' and 'err' are incompatible.
          Type 'AWSError | undefined' is not assignable to type 'AWSError'.
            Type 'undefined' is not assignable to type 'AWSError'.
```

This is the particular code where the error is throwing:

```
export const getSNSClient = (): AWS.SNS => {
  if (tracingEnabled()) {
    const sns = new AWS.SNS()
    return AWSXRay.captureAWSClient(sns)
  }
  return new AWS.SNS()
}
```

I was able to work around this by dropping the explicit return type of `AWS.SNS`. However, now the function is inferring a return type of only `PatchedAWSClient<SNS>`.

I'm not sure if this was intentioned, and also not sure if this is going to cause any issues where I have other methods which expect an interface of `AWS.SNS`.

I am using version `2.488.0` of the `aws-sdk` in my application.

**Comment by purplecode** [comment]
+1

According to the `aws-sdk` implementation ([here](https://github.com/aws/aws-sdk-js/blob/master/lib/response.js#L107) and [here](https://code.amazon.com/packages/NodeJS-aws-sdk/blobs/3b710e630842164c550e4e70149adf93e5257f9c/--/aws-sdk/lib/response.js#L136-L144)), the right typing should be:
```
type Callback<D> = (err: AWS.AWSError | null, data: D) => void;
```

Can it be that both `aws-sdk` ([source](https://github.com/aws/aws-sdk-js/blob/19a5b5936f2356441d9fc02de2c2ca1409439f54/lib/service.d.ts#L38)):
```
callback?: (err: AWSError, data: any) => void
```
and `aws-xray-sdk-node` [source](https://github.com/aws/aws-xray-sdk-node/blob/2.x/packages/core/lib/patchers/aws_p.d.ts#L5):
```
Callback<D> = (err: AWS.AWSError | undefined, data: D) => void;
```
are wrong?

**Comment by willarmiros** [comment]
@purplecode has volunteered to make a PR to resolve this issue, it will be released in v3 of the SDK.

**Comment by willarmiros** [comment]
Hi @duro,
Could you provide a more thorough code snippet to reproduce the error? I tried making a simple TypeScript app with an instrumented SNS client and called `SNS.publish(params)` and it transpiled and ran just fine.
