### ISSUE TITLE
Changelog for 2.4.0 and 2.5.0?

### ISSUE THREAD

**Issue by linjunpop** [aws/aws-xray-sdk-node#223]
There's no Changelog for 2.4.0 and 2.5.0.

**Comment by willarmiros** [comment]
These versions were released from the 2.x branch, so they have a [CHANGELOG](https://github.com/aws/aws-xray-sdk-node/blob/2.x/packages/full_sdk/CHANGELOG.md) there. They will be present in `master` soon once the process to release 3.0 has begun. See #157 for more.

**Comment by linjunpop** [comment]
That's quite misleading as the master has changelogs for `v2.3.0`. It would be appreciated if the CHANGELOG on the master can attach the link to the 2.x branch.
