### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by thomasmichaelwallace** [aws/aws-xray-sdk-node#24]
I've just noticed that v1.2.0 is out- is there anywhere can I find out what bumped the minor version?

**Comment by haotianw465** [comment]
This is the change log https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/CHANGELOG.md

The default AWS parameter whitelist has changed to capture S3 bucket names for all S3 APIs. This will result in behavior change on service graph if you are using X-Ray instrumented S3 calls. This will also impact any manual modification on that whitelist file.

Please let me know if you have any other concerns.

**Comment by thomasmichaelwallace** [comment]
Thanks- I thought it'd be in the root repo folder!
