### ISSUE TITLE
TypeScript definition errors

### ISSUE THREAD

**Issue by jameshartt** [aws/aws-xray-sdk-node#245]
Hi there, seem to be getting some errors when compiling TypeScript with this module.

```
../../node_modules/aws-xray-sdk-core/lib/capture.d.ts:14:9 - error TS2370: A rest parameter must be of an array type.

14   fcn: (...args: S) => T,
           ~~~~~~~~~~


../../node_modules/aws-xray-sdk-core/lib/capture.d.ts:16:5 - error TS2370: A rest parameter must be of an array type.

16 ): (...args: S) => T;
       ~~~~~~~~~~


../../node_modules/aws-xray-sdk-core/lib/utils.d.ts:19:4 - error TS2304: Cannot find name 'Omit'.

19 ): Omit<T, K>;
      ~~~~
```

Using latest version of TypeScript, and downgrading to `3.5.1` doesn't seem to have an effect.

**Comment by willarmiros** [comment]
Hi @jameshartt,
Thanks for raising this issue. Can you please provide snippets of your code where you are using the `captureCallbackFunc` API? It appears that the TS definition of this API is correct, based on the [JSDoc](https://docs.aws.amazon.com/xray-sdk-for-nodejs/latest/reference/module-capture.html) and the [definition file](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/capture.d.ts#L12).

As for the error on `Omit`, that should be a utility type shipped in the latest version of TypeScript. See the [TS docs](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittk).
