### ISSUE TITLE
Sanitize http calls traced with X-Ray

### ISSUE THREAD

**Issue by danilofuchs** [aws/aws-xray-sdk-node#246]
I'm using X-Ray through node's aws-xray-sdk. I am capturing node's native http with 
```javascript
AWSXRay.captureHTTPsGlobal(http, false);
AWSXRay.captureHTTPsGlobal(https, false);
```
This works great, but I need to interface with an API that has a GET endpoint, where a query string contains sensitive user information. I need to be able to sanitize the url, to avoid showing this data in the AWS Console.
In this thread I found something promising when it comes to manipulating segments: https://forums.aws.amazon.com/thread.jspa?threadID=261234&tstart=125.
```javascript
  request.get('http://google.com/img.png')
    .on('response', function(response) {
        var parentSubs = AWSXRay.getSegment().subsegments;
        var subsegment = parentSubs[parentSubs.length -1];
        subsegment.name = response.req.getHeader('host') + response.req.path;
        //...
    });
```
This example seems outdated, as the type definition for `Subsegment | Segment` does not have the property `subsegments`
As I'm using axios to handle requests, how can I implement this behaviour?

**Comment by willarmiros** [comment]
Hi @danilofuchs,
The response on that forums post is the correct way to do what you're describing, however it was written prior to the implementation of TypeScript definitions. So the issue is not that it's outdated but that the TS definitions omitted the `subsegments?: Array<Subsegment>` field for the `Segment` and `Subsegment` classes. If you'd like to open a PR I'd welcome it, otherwise I'll get to it before the next release.

**Comment by danilofuchs** [comment]
Ok! I'll be writing a PR shorly

**Comment by danilofuchs** [comment]
Hello @willarmiros, I am having trouble implementing this feature, using this approach:
```javascript
var parentSubs = AWSXRay.getSegment().subsegments;
var subsegment = parentSubs[parentSubs.length -1];
subsegment.name = response.req.getHeader('host') + response.req.path;
```
I'm considering implementing a first level API for masking HTTP request content before closing a subsegment.

The proposed API would look like this (I'm very open for suggestions):
```javascript
AWSXRay.captureHTTPsGlobal(http, {
  downstreamXRayEnabled: true,
  overrideRequestData: (req) => ({
    url: req.agent.protocol + "//" + req.getHeader("host") + maskPath(req.path),
    method: req.method || ''
  })
});
```

This way, users could easily check if a request matches the one they need to mask out and manipulate the generated subsegment.

AFAIK, all data is injected into the subsegment via [`subsegment.addRemoteRequestData()`](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/patchers/http_p.js#L126), which builds a [`RemoteRequestData`](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/segments/attributes/remote_request_data.js) object. I propose we either:

- Remove the `downstreamXRayEnabled` parameter and instead pass an `options` parameter that accepts an interceptor function, that can manipulate the saved subsegment's data, or...
- Add another (optional) `options` parameter, keeping `downstreamXRayEnabled` as the 3rd parameter.
- Use a function overload pattern so the user can still pass a boolean `downstreamXRayEnabled`, or else the `options` object with other capabilities (this could be confusing).

Only the first approach infers in an API change, but a very manageable one, considering this SDK's 3.0 version is coming soon and users expect breaking changes.

Either way, I'll be happy to make a PR providing those changes.

Also, we could consider using this approach to separate subsegment's names for API calls to many paths of the same host. (forum issue for reference)

**Comment by danilofuchs** [comment]
@willarmiros what do you think of my suggestion? Should I make a PR for it?

**Comment by willarmiros** [comment]
Hi @danilofuchs,

I suppose I'm somewhat confused by the necessity of this addition for your use case. Are you saying that currently the SDK includes your query string in the `url` field of your subsegments? The query string should not be included in `req.path` in the first place. 

If you're more interested in general sanitization of URL paths, we are having an ongoing discussion on how we'd like to do sanitization for everything from URL paths to SQL queries to annotations/metadata across all our SDKs, so we would probably wait on a PR for this.

**Comment by danilofuchs** [comment]
It seems like `axios` adds the query string to `req.path`. I'm looking into other request providers that don't have this behaviour. In the meantime, I'm disabling X-Ray tracing for http requests.

I'm happy to hear you are developing a sanitizing solution.

**Comment by willarmiros** [comment]
Actually it looks like we're wrong on this one. According to the node [documentation](https://nodejs.org/api/http.html#http_http_request_url_options_callback):

> path: Request path. Should include query string if any. E.G. '/index.html?page=12'. An exception is thrown when the request path contains illegal characters. Currently, only spaces are rejected but that may change in the future. Default: '/'.

So what really what we should do is sanitize the query string out of `req.path` in both [remoteRequestData.js](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/segments/attributes/remote_request_data.js) and from logging statements in [http_p.js](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/patchers/http_p.js), since the behavior of the other SDKs is to assume the query string contains sensitive data and sensor it by default. 

If you'd like to open a PR to implement this behavior I'd be open to it.

**Comment by danilofuchs** [comment]
I'm working on the fix right now and will send a PR.

**Comment by danilofuchs** [comment]
Here is the PR: https://github.com/aws/aws-xray-sdk-node/pull/251

**Comment by joebowbeer** [comment]
By the way, we are seeing a crash because req.agent is undefined:

`    url: req.agent.protocol + "//" + req.getHeader("host") + maskPath(req.path),`
