### ISSUE TITLE
TypeScript compiler hangs when wrapping aws-sdk

### ISSUE THREAD

**Issue by aecorredor** [aws/aws-xray-sdk-node#253]
There's a really strange issue going on with this package when trying to wrap the `aws-sdk` with the `aws-xray-sdk` using TypeScript. If you try to follow this guide https://serverless-stack.com/chapters/tracing-serverless-apps-with-x-ray.html, but instead use `import` statements, `tsc` will hang. It happens when running the actual compiler or in VSCode.

Example:

```js
import AWS from 'aws-sdk';
import AWSXRay from 'aws-xray-sdk-core';

// Do not enable tracing for 'invoke local'
const AWSWrapped = process.env.IS_LOCAL ? AWS : AWSXRay.captureAWS(AWS);

export default AWSWrapped;
```

or with the `aws-xray-sdk` directly like in https://github.com/AnomalyInnovations/serverless-stack-demo-ext-api/blob/master/libs/aws-sdk.js:

```js
import AWS from 'aws-sdk';
import AWSXRay from 'aws-xray-sdk';

// Do not enable tracing for 'invoke local'
const AWSWrapped = process.env.IS_LOCAL ? aws : xray.captureAWS(aws);

export default AWSWrapped;
```

Is anyone experiencing the same thing? any clues?

**Comment by aecorredor** [comment]
So I got this working with a piece of code that seems like a hack:

```js
// The aws-xray-sdk needs bring aws-sdk using require.
/* eslint-disable @typescript-eslint/no-var-requires */

// aws-sdk is in the node environment on every lambda.
/* eslint-disable import/no-extraneous-dependencies */

import AWSXRay from 'aws-xray-sdk';

// AWSXRay does not work when running locally.
// https://stackoverflow.com/questions/53546181/errorfailed-to-get-the-current-sub-segment-from-the-context-when-use-aws-x-ra
const AWS = process.env.IS_LOCAL
  ? require('aws-sdk')
  : AWSXRay.captureAWS(require('aws-sdk'));

export default AWS as ReturnType<typeof AWSXRay.captureAWS>;
```

This way I end up keeping the types for the exported patched AWS object.

There are some other problems with that though, like `PatchedAWSClient<DynamoDB>` being incorrect. I get the following type error when trying to pass a dynamo object to `dynamoose.setDDB` (which was working before wrapping the original sdk):

```
Type 'AWSError | undefined' is not assignable to type 'AWSError'.
            Type 'undefined' is not assignable to type 'AWSError'
```.

I fixed that by just doing `dynamoose.setDDB(dynamoDb as AWS.DynamoDB);`

**Comment by willarmiros** [comment]
Hi @aecorredor,
Thanks for raising this issue. There are certainly some issues with how types for this SDK were defined for patched AWS objects, and a similar error was pointed out in #220 (although it wasn't clear if that was a bug from us, the AWS SDK, or both). Regardless, in the next major version we are removing our dependency on the AWS SDK, and with it changing the patched AWS SDK types as `any`. You should be able to cast them to their original types if desired from there.

**Comment by aecorredor** [comment]
@willarmiros thanks for the quick response. That makes sense. I'm also guessing that the problem with `tsc` hanging will probably also go away once you remove the `aws-sdk` dependency. I'm thinking that there's some kind of infinite loop happening when the compiler sees `aws-sdk` and `aws-xray-sdk` imported in the same file.

**Comment by willarmiros** [comment]
Resolving since these definitions are removed in 3.0.0-alpha.2
