### ISSUE TITLE
When adding object containing an array to meta data, the array is empty

### ISSUE THREAD

**Issue by chearmstrong** [aws/aws-xray-sdk-node#260]
![image](https://user-images.githubusercontent.com/10651067/75975730-f4b60700-5ed0-11ea-8099-8cccf1694f24.png)

Both the `devices` and `inputs` arrays should contain values - when logging the same things to CW logs (using `console.log`) I can see them. It only works (I can see the values) if I use `JSON.stringify` on the whole object.

Happens on `3.0.0-alpha.1`, `2.5.0-experimental.1` and `2.5.0`.

Interestingly, if I add the whole event object, it doesn't happen all all arrays. For example the values in these headers.

![image](https://user-images.githubusercontent.com/10651067/75976444-59259600-5ed2-11ea-964d-abe7843756e0.png)

But when logging the full event object, it still removes the values from the `inputs` for example.

![image](https://user-images.githubusercontent.com/10651067/75976526-84a88080-5ed2-11ea-8da2-55b35dd262e7.png)

Am I missing something?

**Comment by willarmiros** [comment]
How are you making log statements? This is the expected format for logging with the X-Ray SDK's logger, it's a string message as the first argument followed by a object or string metadata argument:

```
AWSXRay.getLogger().info('message', metadataObj);
```

The logger uses `JSON.stringify()` on the metadata under the hood anyway, so any object should be fully printed. Here's the [metadata formatter](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/logger.js#L74).

**Comment by GrzegorzKozub** [comment]
This happens to me when using [addMetadata](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-segment.html) method from X-Ray SDK for Node.js. 

Given `subsegment` is an instance of `AWSXRay` and `result` is a JSON object (not a string), I'm passing a JSON object like so:
```
subsegment.addMetadata('result', result, 'response');
```
Then, when looking at the metadata in xRay I can see the arrays on my object are empty. In my case these arrays are arrays of objects, like this:
```
[ { "foo" : "bar", "baz" : 2 }, { "foo" : "something", "baz" : 123 }, ... ]
```

**Comment by willarmiros** [comment]
Hi @GrzegorzKozub, 

Thanks for raising this again. I mistakenly thought @chearmstrong was talking about the SDK's logger beforehand, not subsegment metadata. I was able to reproduce this issue, and it is a bug with the X-Ray backend service. We will work on fixing it as soon as we can.

**Comment by chearmstrong** [comment]
Thanks for confirming it's a bug (and sorry for not being able to respond quickly). Will watch out for the fix.

**Comment by willarmiros** [comment]
This issue has been fixed, and such nested objects should now appear normally in your metadata :)
