### ISSUE TITLE
Postgres subsegments not working

### ISSUE THREAD

**Issue by julianbonomini** [aws/aws-xray-sdk-node#266]
Hi, I'm just encountering some problems using x-ray-postgres.

the documentation shows basically the same code snippet for manual and automatically, but they do not work.

Any ideas why? 

```
import * as AWSXRay from 'aws-xray-sdk';
import * as _pg from 'pg';

const pg = AWSXRay.capturePostgres(_pg);
```
```
constructor() {
  this.pool = new pg.Pool(configuration.rds);
}
```

and then the query is being performed like this:
```
async query(sql: QueryConfig | string, values?: Array<any>): Promise<QueryResult> {
  const client = await this.pool.connect();
  try {
    return await client.query(sql, values);
  } finally {
    client.release();
  }
}
```

**Comment by willarmiros** [comment]
Hi @julianbonomini, 
Could you try to call `capturePostgres` on `require('pg')`, rather than using ES6 import syntax? Because of the way we monkey patch SQL libraries, there have been some issues with using the import syntax.

**Comment by julianbonomini** [comment]
Still working funny, we moved to manual supplementation. Thank you!

Now we are facing problems with the subsegment tho. Sometimes is undefined (we are using experimental). 

But thanks! This issue can be closed!
