### ISSUE TITLE
SQS ns.run or ns.bind error

### ISSUE THREAD

**Issue by auberryberry** [aws/aws-xray-sdk-node#280]
OK, folks, finally reached the point where I can't dig through cls-hooked or x-ray anymore, We have a couple of our microservices tracing fine until hitting SQS, reinstrumenting the services on the other side with the TraceID seems to be an issue.

https://docs.aws.amazon.com/xray/latest/devguide/xray-services-sqs.html
This example in Java....whats the equivalent in javascript???? Super unhelpful documentation

We're using Node 12, async/await, I've tried experimental and 3.0 alpha versions of x-ray for node,

I've got the AWSTraceHeader from the sqs message Attributes, no worries, I can build a new segment, but setting the segment causes an error. 
No context available. ns.run() or ns.bind() must be called first.

```
ns.run(()=>{
  const traceData = aws.XRay.utils.processTraceData(
    message.Attributes.AWSTraceHeader
  )
  const ns = aws.XRay.getNamespace()
    aws.XRay.setSegment(currentSegment)
  })
```
This doesn't seem to work either so I'm at a total loss. seeing nothing from x-ray demon with the above code..

**Comment by willarmiros** [comment]
Hi @auberryberry, 
It looks like you might have a slight bug in your custom X-Ray solution there. I'd suggest changing it to something like:

```js
const AWSXRay = require('aws-xray-sdk');

const traceData = AWSXRay.utils.processTraceData(message.Attributes.AWSTraceHeader);

var segment = new AWSXRay.Segment(name, traceData.Root, traceData.Parent);
var ns = AWSXRay.getNamespace();  // Note that you must call ns.run after getting the X-Ray namespace

ns.run(function () {
  AWSXRay.setSegment(segment);
  // your logic ....
});
```

This is based on the developing custom solutions [documentation](https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#developing-custom-solutions-using-automatic-mode).

**Comment by auberryberry** [comment]
Hey @willarmiros  thanks for the reply, this is all happening in an async function, so you're saying that any dynamo calls or anything that's wrapped or patched with x-ray needs to happen in the ns.run callback? is ns.runPromise better here?

**Comment by willarmiros** [comment]
> so you're saying that any dynamo calls or anything that's wrapped or patched with x-ray needs to happen in the ns.run callback?

Yes, anything you want traced has to be within the ns.run() callback in order for it to have the context necessary to generate subsegments.

> is ns.runPromise better here?

Not sure really, we use `ns.run` everywhere but you're welcome to try with either. Also, to be sure, you're not using a web framework to handle these messages right?

**Comment by auberryberry** [comment]
Thanks will I've got this sorted now, no web framework, all node :)
