### ISSUE TITLE
aws-xray-sdk-core makes bad side effects on nodejs8.10 runtime ("null" return value)

### ISSUE THREAD

**Issue by mooyoul** [aws/aws-xray-sdk-node#29]
I've found super annoying issue after migrating to nodejs8.10 runtime with async handler.

## Short Reproducible code

```js
"use strict";

module.exports.foo = async (event) => {
  console.log("got event: %j", event);

  require("aws-xray-sdk-core");

  return { data: "oh my!" };
};
```

## Expected Result

Lambda Execution result should be `{ data: "oh my!" }`.

## Actual Result

On lambda nodejs8.10 runtime: returns `null`.
On native node 8.10 docker image: returns `{ data: "oh my!" }`

If comment `require("aws-xray-sdk-core")` line, lambda nodejs8.10 runtime returns expected `{ data: "oh my!" }`.

I wasted about 8 hours to investigate the root cause of this problem. I could not find any documents. 
At least please write compatibility note about node.js runtime on documentation for customers.

**Comment by haotianw465** [comment]
Sorry about the inconvenience. We are in a testing process with the new Lambda 8.10 runtime to see what works, what breaks and what needs to be done to fix the issues. We will have our doc team soon post a note in our user guide about the current SDK doesn't work with the new async handler.

**Comment by haotianw465** [comment]
I successfully reproduced the issue with the example you gave. I'm closing this in favor of https://github.com/aws/aws-xray-sdk-node/issues/27 so we all have a single place to share updates/findings/fixes.

We will continue to look at 8.10 support and will update #27 as soon as we have any new update.

**Comment by mooyoul** [comment]
okay, i'll share some findings to #27. thanks @haotianw465 !
