### ISSUE TITLE
Lambda crashes randomly (Error: socket hang up) after adding X-Ray

### ISSUE THREAD

**Issue by vladgolubev** [aws/aws-xray-sdk-node#31]
Hey, 

every single of 400 our Lambda function randomly crashes after adding X-Ray SDK.

⬇️ Stack trace ⬇️
```
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1124:19)
    at TLSSocket.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at /var/task/node_modules/async-listener/glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)
```

I suspect this is because of [`async-listener`](https://github.com/othiym23/async-listener) package which monkey-patches stuff and causes problems with Node 8.10 in Lambda (see https://github.com/aws/aws-xray-sdk-node/issues/27)

When I run `yarn why async-listener` and xray-sdk is the only package depending on it.

```
$ yarn why async-listener 
yarn why v1.6.0-20180405.1011
[1/4] 🤔  Why do we have the module "async-listener"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "async-listener@0.6.9"
info Reasons this module exists
   - "aws-xray-sdk-core#continuation-local-storage" depends on it
   - Hoisted from "aws-xray-sdk-core#continuation-local-storage#async-listener"
```

Upgrading from node 6 to 8 didn't help.

Any clue how to fix it? We want to use AWS X-Ray but we don't want our Lambda to crash randomly and confuse users.

**Comment by KnupMan** [comment]
So it's the second problem with `async-listener` in X-Ray SDK. The first one was with overriding by `async-listener` `global.Promise` object (https://github.com/aws/aws-xray-sdk-node/issues/27), so it's making problems for AWS developers to fix those issues as well.

**Comment by vladgolubev** [comment]
@haotianw465 thanks for bringing this up again. You're right, I've stopped seeing this issue for a while! The issue can be closed now, thanks!
