### ISSUE TITLE
SQS - "Error: Failed to get the current sub/segment from the context."

### ISSUE THREAD

**Issue by fidian** [aws/aws-xray-sdk-node#310]
We're trying to implement X-Ray and it's causing issues accessing SQS. The code is running on an EC2 instance. I don't see any additional tips in the README, yet I am unable to make this work.

Sample code:

```
const aws = require('aws-sdk');                
const xray = require('aws-xray-sdk');                                                       
const modified = xray.captureAWS(aws);                                                      
const sqs = new modified.SQS({
    region: 'us-east-1'
}); 
sqs.receiveMessage({                                                                        
    QueueUrl: 'https://sqs.us-east-1.amazonaws.com/.....hidden...../.....hidden.....',
    VisibilityTimeout: 600
}, (err, response) => {                                                                     
    if (err) {
        console.log('Error');                                                               
        console.log(err);                                                                   
    } else {
        console.log('Success');                                                             
        console.log(response);                                                              
    }   
});
```

Result:

```
/home/user/test-program/node_modules/aws-xray-sdk-core/lib/context_utils.js:21
        throw new Error(message);
        ^

Error: Failed to get the current sub/segment from the context.
    at Object.contextMissingRuntimeError [as contextMissing] (/home/user/test-program/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)
    at Object.getSegment (/home/user/test-program/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)
    at Object.resolveSegment (/home/user/test-program/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)
    at features.constructor.captureAWSRequest [as customRequestHandler] (/home/user/test-program/node_modules/aws-xray-sdk-core/lib/patchers/aws_p.js:60:29)
    at features.constructor.addAllRequestListeners (/home/user/test-program/node_modules/aws-sdk/lib/service.js:279:34)
    at features.constructor.makeRequest (/home/takins5/user/test-program/node_modules/aws-sdk/lib/service.js:203:10)
    at features.constructor.svc.<computed> [as receiveMessage] (/home/user/test-program/node_modules/aws-sdk/lib/service.js:677:23)
    at Object.<anonymous> (/home/user/test-program/test.js:8:5)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
```

**Comment by willarmiros** [comment]
Hi @fidian, 
This problem is occurring because when you make a request with an instrumented AWS SDK client like yours, the X-Ray SDK attempts to automatically begin a subsegment to trace that SQS request. The X-Ray SDK expects a segment to be started before any subsegments are created. If there is no segment available, as in your case, it throws the error you see.

If you're using an express app and defining routes, the SDK will automatically create a segment for you within those defined routes. Otherwise, see our section on [developing custom solutions](https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#developing-custom-solutions-using-automatic-mode) to manually begin a segment, and then once you have begun the segment, you should be able to make instrumented AWS SDK requests. Please let us know if this resolves your issue.

**Comment by fidian** [comment]
I have added the following lines to my test program and it is still not working. I'm trying to follow the docs but am having a very difficult time with getting this to work. Searches on Google for people using X-Ray all seem to focus on using it as middleware. Sorry to be a pain, but could you help point me to what is wrong?

```
...
const modified = xray.captureAWS(aws);

// Begin added code
const segment = new xray.Segment('job-runner');
const ns = xray.getNamespace();
ns.run(() => {
    console.log('setSegment');
    xray.setSegment(segment);
});
// End added code

const sqs = new modified.SQS({
...
```

Running the test program still produces the same error during the call to SQS.

**Comment by willarmiros** [comment]
No problem, all you need to do is move your SQS requests *inside* the `ns.run` block. Something like:

```js
const modified = xray.captureAWS(aws);

// Begin added code
const segment = new xray.Segment('job-runner');
const ns = xray.getNamespace();
ns.run(() => {
    console.log('setSegment');
    xray.setSegment(segment);
    const sqs = new modified.SQS({
        // config
    });
    sqs.receiveMessage(...);
    ....
    segment.close();
});
// End added code


```

**Comment by fidian** [comment]
That was the crucial bit I needed. Thank you for helping me out! I didn't get that impression from reading [Ttis section](https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#developing-custom-solutions-using-automatic-mode) of the documentation. I don't read anything that implies that my calls to AWS need to be within the namespace. Or maybe an example somewhere that doesn't rely on middleware?

Anyway, you've been extremely helpful and quick with your responses even though the issue tracker isn't a great spot for questions. Thank you for your assistance!
