### ISSUE TITLE
guard against undefined req.agent

### ISSUE THREAD

**Issue by joebowbeer** [aws/aws-xray-sdk-node#312]
We're seeing a crash because `req.agent` is undefined at [remote_request_data.js#L17](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/segments/attributes/remote_request_data.js#L17
). The underlying problem could certainly be ours but regardless I think some defensive coding would be advised:

```
url: (req.agent.protocol + '//' + req.getHeader('host') +  stripQueryStringFromPath(req.path)) || '',
```

**Comment by willarmiros** [comment]
Hi @joebowbeer, 
I've followed up on the PR!
