### ISSUE TITLE
When is the new release date of the sdk?

### ISSUE THREAD

**Issue by nicodeg87** [aws/aws-xray-sdk-node#322]
Hi guys,

I see that on master there is a much simplified version of middleware usage after this commit: [https://github.com/aws/aws-xray-sdk-node/commit/a2344c47f60722b2b3b74eea5da897e86c09c5b4](https://github.com/aws/aws-xray-sdk-node/commit/a2344c47f60722b2b3b74eea5da897e86c09c5b4) . This is a great improvement as for example our middleware on Koa will be just a few lines. 

When do you have planned to release the next version of the SDK with this change? It has been more than 1 month since the last version was released :).

Thanks in advance.

**Comment by willarmiros** [comment]
Hello,

We are actually about to merge our own community-contributed piece of Koa middleware in #317! We will make a new release of the SDK after that is merged, but I cannot give an exact date. Feel free to try our vended Koa middleware or continue to use your own :)

**Comment by pushchris** [comment]
It looks like the PR for Koa was merged. Any updates on when a release will be put out that includes those changes?

**Comment by cmckni3** [comment]
> It looks like the PR for Koa was merged. Any updates on when a release will be put out that includes those changes?

Yep, I had to tweak the coa middleware to work because of the logger refactor. `middlewareLog is not a function` error otherwise.

**Comment by sbe-arg** [comment]
any updates on release date?

**Comment by willarmiros** [comment]
@cmckni3 can you elaborate on your comment? Were you experiencing a bug with the (as of yet unreleased) Koa support package? 

As for a release, sorry for not corresponding earlier as I've been occupied with another project. I can't give exact dates but will prioritize a release in the near future and update this issue when it's done.

**Comment by cmckni3** [comment]
@willarmiros i copied the koa middleware from the contrib folder. It doesn’t work with the core package on npm because `middlewareLog` is missing.

**Comment by willarmiros** [comment]
3.2.0 is released.
