### ISSUE TITLE
Use lodash instead of underscore

### ISSUE THREAD

**Issue by nolde** [aws/aws-xray-sdk-node#33]
According to npm, [lodash](https://www.npmjs.com/package/lodash) has around **14.5 million** downloads per week, whereas [underscore](https://www.npmjs.com/package/underscore) has less than 5 million downloads per week. Both libraries have around the same capabilities, but lodash is massively popular.

The reason for this request is that having both libraries demands more npm download time and generates larger bundles; the sdk core is used by lambda functions, and any extra libraries loaded increase the size of the bundle. Also, according to AWS own tips, developers should be using tools like Browserify to bundle up the functions, so this is even more important ([see video](https://youtu.be/oQFORsso2go?t=10m22s)). Also, requesting the target functions instead of the whole library would help.

**Comment by awssandra** [comment]
Hi nolde,

Thank you for taking the time to comment. Pruning down the dependencies is a known item on our backlog we hope to address in the near future. We agree that the current size of the SDK and it's dependencies has much to be improved upon and understand the gains of reducing this. 

See related post on dependencies: https://github.com/aws/aws-xray-sdk-node/issues/10

As always, we hope the community will continue to reach out to us for improvements, and PRs are always welcome. We hope to address these issues as a whole as soon as we are able.

Thanks,
Sandra
