### ISSUE TITLE
PG capture does not work well with queryConfig objects.

### ISSUE THREAD

**Issue by nmaves** [aws/aws-xray-sdk-node#335]
Per the PG documentation, you should be able to pass a queryConfig object with the shape as the following.  This is not working with the AWSXRay.capturePostgres().  I think the issue is around the fact that we are not passing a callback in but that should trigger the promise returned and it is not.

```
interface QueryConfig {
  // the raw query text
  text: string;
  // an array of query parameters
  values?: Array<mixed>;
  // name of the query - used for prepared statements
  name?: string;
  // by default rows come out as a key/value pair for each row
  // pass the string 'array' here to receive rows as an array of values
  rowMode?: string;
  // custom type parsers just for this query result
  types?: Types;
}
```

**Comment by nmaves** [comment]
Looks like you can just update this https://github.com/aws/aws-xray-sdk-node/blob/bd2a8f2554c3969a2b47afb59c1a7085b54f3cd8/packages/postgres/lib/postgres_p.js#L41

to be the following

```
args.callback = argsObj[2] || argsObj[1] || argsObj[0].callback;
```

**Comment by awssandra** [comment]
Hi nmaves,

Thanks so much for the deep dive! If you'd like, you can open a PR and we can merge this in, and we can credit you as a contributor.

Can you confirm which version of PG you're using? We'll need to make sure we keep backwards compatibility.

Thanks!
Sandra

**Comment by nmaves** [comment]
@awssandra We are using node-postgres 8.3.3
