### ISSUE TITLE
Support for pg 7.4.X version

### ISSUE THREAD

**Issue by ashwgupt** [aws/aws-xray-sdk-node#34]
After investing plenty of time on trying to make XRay tracing work for our Postgress client we realised that, it might be a version compatibility issue between **aws-sdk** and **pg** library.

We are using 
```
"aws-xray-sdk": "1.2.0",
"pg": "7.4.1",
```

and the below code snippet to enable tracing for our PG Client
```
const AWSXRay = require('aws-xray-sdk');
const pg = AWSXRay.capturePostgres(require('pg'));
client = new pg.Client(config);
AWSXRay.capturePromise();
```

But we get error with our client instance when invoked on AWS saying,
```
{ TypeError: query.on is not a function
at Client.captureQuery [as query] (/var/task/node_modules/@gdw/postgres-client/node_modules/aws-xray-sdk-postgres/lib/postgres_p.js:67:13)
at PostgresClient.findBy (/var/task/node_modules/@gdw/postgres-client/lib/PostgresClient.js:130:28)
at CustomerRepository.findActiveCustomers (/var/task/lib/CustomerRepository.js:68:35)
at CustomerService.findCustomerAccounts (/var/task/lib/CustomerService.js:109:40)
at /var/task/lib/Customers.js:76:38
at /var/task/node_modules/@gdw/postgres-client/lib/PostgresClient.js:176:20
at /var/task/node_modules/@gdw/postgres-client/node_modules/continuation-local-storage/context.js:84:17
...
```

Can you please confirm is there is an version compatibility limitation between pg and aws-sdk?

**Comment by haotianw465** [comment]
Hi,

This might be similar to #19. Are you invoking the pg client by using `await client.query()` or other syntax?

**Comment by daniel-cottone** [comment]
Are there any plans on adding support for newer versions of postgres?

**Comment by haotianw465** [comment]
Hi @daniel-cottone @hannesj , support for pg 7.x is in our backlog. We will fix the `peerDeps` for now and update this issue once we make progress on the new pg major version support. Thank you for your patience. A PR is always welcome.

**Comment by ebaioni** [comment]
+1 for this.
We are facing the same issue.
Thanks

**Comment by jafl** [comment]
I created #64 to address this.

**Comment by haotianw465** [comment]
This is released as part of `v2.1.0` thanks for #64 from @jafl

**Comment by chrisradek** [comment]
Reopening. #64 added support for using `pg` with the promise-based API, but not the callback-style API.

So the following will work:
```javascript
client.connect()
        .then(() => {
            return client.query('select * from foo');
        })
        .then((data) => {
            console.log(data);
            return client.end();
        });
```
but this will still cause an error (when using xray):
```javascript
client.connect(function(err) {
        if (err) {
            throw err;
        }
        client.query('select * from foo', function(err, results) {
            if (err) {
                console.error(err);
            } else {
                console.log(results);
            }
            client.end();
        });
    });
```

**Comment by jafl** [comment]
I found the issue:  `client.query` return `null` when not using promises.  I submitted #77

This is tested with pg 7.7.1
