### ISSUE TITLE
Is it possible to log lambda X-Ray traces, to same lambda cloudwatch loggroup?

### ISSUE THREAD

**Issue by bala1074** [aws/aws-xray-sdk-node#347]
Will it be possible to use **shimmerjs** to do monkeypatching to aws-x-ray-sdk 

```
START RequestId: f5507533-9175-4dea-83b0-a71384c4f507 Version: $LATEST

<<<<<<<<<<<<<<<<<Log X-ray traces as part of same lambda loggroup logs>>>>>>>>>>>>>>>>>>>

END RequestId: f5507533-9175-4dea-83b0-a71384c4f507
REPORT RequestId: f5507533-9175-4dea-83b0-a71384c4f507	Duration: 100.72 ms	Billed Duration: 200 ms	Memory Size: 1024 MB	Max Memory Used: 90 MB	Init Duration: 455.37 ms	
XRAY TraceId: 1-5f92b333-70350ac7708cb2b827d1dd11	SegmentId: 68798e5d297dfcde	Sampled: true
```

**Comment by willarmiros** [comment]
Hi @bala1074,

I don't think we'd be able to prioritize rewriting all of our patchers to use Shimmer at this time. I also don't understand how that would relate to Logging in Lambda, could you elaborate a bit more on your use case and desired state?

**Comment by bala1074** [comment]
@willarmiros thank you for the response.

Actually, I am working on end to end tracing for serverless. To implement end to end tracing, I was looking into the possible Serverless Lambda triggers (like API Gateway, SQS, SNS, S3, CloudWatch Events, DynamoDB Streams, Step Functions ..etc.,), I enabled X-RAY for the lambda function and get traces but not able to see trigger related traces in X-RAY.

**Question1:** Will it be possible to get lambda trigger information in X-Ray for all possible triggers?

I assume, if it is not possible to get the trigger information in X-RAY for all possible triggers, So I decided to use lambda functions event object to derive the trigger using https://gist.github.com/jeshan/52cb021fd20d871c56ad5ce6d2654d7b

Once I derive the trigger from event object, I do console to clouwatch loggroup of that lambda function.

Finally, I am collecting cloudwatch logs  to get the trigger information + collecting x-ray traces to get lambda traces   

**Question2:** To simplify the correlatation of the **trigger + xray traces**, I am thinking to console X-Ray traces to cloudwatch logs.

I was collecting **XRAY TraceId** from the cloudwatch logs **REPORT** 
```
START RequestId: f5507533-9175-4dea-83b0-a71384c4f507 Version: $LATEST
<<<<<<<<<<<<<<<<<Log X-ray traces as part of same lambda loggroup logs>>>>>>>>>>>>>>>>>>>
END RequestId: f5507533-9175-4dea-83b0-a71384c4f507
**REPORT** RequestId: f5507533-9175-4dea-83b0-a71384c4f507	Duration: 100.72 ms	Billed Duration: 200 ms	Memory Size: 1024 MB	Max Memory Used: 90 MB	Init Duration: 455.37 ms	
**XRAY TraceId: 1-5f92b333-70350ac7708cb2b827d1dd11**	SegmentId: 68798e5d297dfcde	Sampled: true
```
and then using XRAY TraceId, I am quering the x-ray api's to collect traces. 
And all operations here are synchronous and dependent to each other. Like collect x-ray-id and then collect traces from x-ray.

To simplify that, Is It possible to **log x-ray traces** along with **XRAY TraceId** in the report section of cloudwatch logs

**Comment by willarmiros** [comment]
Hi @bala1074,

Q1: Today, as I'm sure you've noticed, SQS and many other batching services triggering Lambda do not make a connected trace. #208 tracks that feature request and is something the X-Ray team is actively working on and will update when it is available. For now parsing the trigger from the event and using that to connect your traces manually sounds like a good approach for your use case.

Q2: You can pretty-print the entire segment object in your Lambda handler code by simply doing:

```js
console.log(JSON.stringify(AWSXRay.getSegment(), null, 2));
```

This will print the segment object in your logs, which will include its trace ID. Hope this helps!

**Comment by bala1074** [comment]
Hi @willarmiros,
Q2: I am able to get the x-ray traces for the particular segment, not entire traces. Would it be possible to get the entire trace object (contains all segment traces) in logs. Or else, Is there any possibility to programmatically Identify segment and log traces for all segments with minor code changes by implementing a serverless plugin. I tried by enabling debug flag from the lambda environment AWS_XRAY_DEBUG_MODE, Is it recommended in production?

**Comment by willarmiros** [comment]
It is not really possible to log the entire trace in real time from a particular application, e.g. Lambda. That's because a trace is by definition a collection of segments from several different services, so your Lambda function would have no way of knowing the contents of the trace contributed by other services in real time. 

I would not recommend `AWS_XRAY_DEBUG_MODE` logging in production, it can be quite verbose and pollute your logs.
