### ISSUE TITLE
error `Module @types/qs` has no exported member 'ParsedQs'

### ISSUE THREAD

**Issue by andreasgrimm** [aws/aws-xray-sdk-node#358]
Using `node` and `typescript` on an existing project I added the X-Ray sdk `npm i aws-xray-sdk` and `tsc` compiled and got the error 

`Module '"    /node_modules/@types/qs"' has no exported member 'ParsedQs'`

In a previous occasion this worked: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49331
.. which is "delete the @types/qs section from yarn.lock and run yarn again", but not this time.

Other googled solutions like `rm -rf node_modules package-lock.json && npm i` also didn't work.

Playing with different installed versions of `@types/qs`, `@types/express` and `@types/express-serve-static-core` (which is also one of the projects dependencies) didn't help either.

Does anyone have any idea how to solve this?

**Comment by willarmiros** [comment]
Hi @andreasgrimm,

Is `@types/qs` a transitive dependency of our `aws-xray-sdk-express` package (specifically the `@types/express` package)? I'm afraid we can't update DefinitelyTyped dependencies, so not sure what resolution action we can take in this repo.

**Comment by andreasgrimm** [comment]
Hi @willarmiros,

yes, `@types/qs` is a transitive dependency of the `aws-xray-sdk-express` package (via the `@types/express` package).
