### ISSUE TITLE
AWS Xray trace for Kafka and redis

### ISSUE THREAD

**Issue by becerriljc** [aws/aws-xray-sdk-node#359]
Hi everyone, i have a question...

Is There a way to trace messages consumed from MKS Kafka and saved into Redis AWS????

**Comment by willarmiros** [comment]
@becerriljc Here is a blog post for tracing Kafka messages using the X-Ray SDK: https://aws.amazon.com/blogs/opensource/tracing-performance-messaging-applications-kafka-aws-x-ray/

The post is for the Java SDK, but the same concepts apply for tracing Kafka messages end-to-end with the Node SDK. 
We don't yet have support for tracing Redis or other in-memory datastores yet. #26 is currently open as a feature request for that, so I'm going to close this to prevent duplication. Please follow up if you have further questions.
