### ISSUE TITLE
How to instrument out-of-request code?

### ISSUE THREAD

**Issue by rosswilson** [aws/aws-xray-sdk-node#36]
We make requests to S3 outside of a normal request, e.g. on service start-up and then periodically. This causes errors as X-Ray tries to retrieve the current segment from the non-existing request context.

I found some guidance for [solving this with the Java SDK](https://docs.aws.amazon.com/xray/latest/devguide/scorekeep-startup.html), but I can't find any for Node.js.

Is there guidance on how to instrument these out-of-request activities?

**Comment by awssandra** [comment]
Hi rosswillson,

There's a few options, depending if you're running in automatic or manual mode. I'll list the automatic mode solution.  You'll need to encapsulate the S3 code in it's own namespace wrapper and capture it in a separate segment, as shown below.

```node
var Segment = AWSXRay.Segment;

var seg = new Segment('name-here');
var ns = AWSXRay.getNamespace();
ns.run(function () {
  AWSXRay.setSegment(seg);

  // Call to S3

  seg.close();
});
```

 Let me know if this works for you.

Thanks!
Sandra

**Comment by rosswilson** [comment]
Thanks @awssandra, that sounds like it'll do the trick.
