### ISSUE TITLE
Remove pkginfo dependency

### ISSUE THREAD

**Issue by chris-pardy** [aws/aws-xray-sdk-node#368]
The pkginfo module causes issues with aws-xray-sdk-core being bundled by tools like rollup. This is described in issue #338. Most of the discussion in that issue centered around cls-hooked which by far causes bigger issues (Node core dumping) however pkginfo also breaks when it's used outside of a standard node environment.

Usage of pkginfo is limited to an invocation in the aws-xray-sdk-core (https://github.com/aws/aws-xray-sdk-node/blob/dd34e7e2c6f4267123707e166d2320d4bdfd14b3/packages/core/lib/aws-xray.js#L9) and a repeated invocation in the full sdk https://github.com/aws/aws-xray-sdk-node/blob/dd34e7e2c6f4267123707e166d2320d4bdfd14b3/packages/full_sdk/lib/index.js#L8

In both cases the the invocation of pkginfo could be wrapped in a try catch block to simply suppress errors (the pkginfo module is already skipped when moduel.filename is undefined) or the code could be replaced with an import of the package.json file which we know the relative path to. Additionally any fields that are being set by pkginfo should be called out in the .d.ts file for these modules.

**Comment by willarmiros** [comment]
Hi @chris-pardy,
Thanks for raising this and apologies for the delay on my follow-up. Definitely interesting that the results of `pkginfo` seem to be discarded like that. I will test out your PR and follow up over there.

**Comment by chris-pardy** [comment]
> Hi @chris-pardy,
> Thanks for raising this and apologies for the delay on my follow-up. Definitely interesting that the results of `pkginfo` seem to be discarded like that. I will test out your PR and follow up over there.

Thanks, I would agree that the fact that `pkginfo` fields were discarded is odd and probably a mistake. As I called out in this issue it's pretty easy to ditch `pkginfo` even if those fields are wanted. Is be happy to rework that PR to first fix the overwriting then get rid of `pkginfo` then remove the dependency if that's desired.

**Comment by willarmiros** [comment]
Just followed up on the PR, if you are able to modify it to remove `pkginfo` while still maintaining those fields then I'd be ok with the change. But it must still ensure that those version and package fields are maintained in all use cases.

**Comment by chris-pardy** [comment]
Some notes on the issue with `pkginfo` in a bundled environment.

The `pkginfo` package uses a recursive `find` operation to traverse up the directory tree until it successfully requires `package.json`. In the case where there is no parent directory, or if the directory is undefined pkginfo throws an error [*source*](https://github.com/indexzero/node-pkginfo/blob/f4e90ac77034ee9eb3dd7aafc56657d7376795a8/lib/pkginfo.js#L95). This will fail or perhaps succeed in unexpected ways when bundled code leverages pkginfo. The failure is caused by the fact that the module invoking pkginfo will no longer be in the same or a child directory of the package.json file. What makes this especially problematic is that pkginfo uses itself to export fields from its package.json file [*source*](https://github.com/indexzero/node-pkginfo/blob/f4e90ac77034ee9eb3dd7aafc56657d7376795a8/lib/pkginfo.js#L129) This means that simply requiring pkginfo in bundled code is enough to cause an error.

Different bundlers will be subjected to issues with pkginfo differently, largely depending on how they translate `require` calls, and specifically ones with dynamic paths. Rollup is particularly problematic as it generally leaves the dynamic `require` calls that pkginfo makes in place but hoists the `require('pkginfo')` call outside of the conditional `module.filename` check that is done I believe to make the code safe for bundlers.
