### ISSUE TITLE
Need the parentId / root traceId for consuming messages from SQS

### ISSUE THREAD

**Issue by mattcasey** [aws/aws-xray-sdk-node#37]
Hi, we are trying to pass trace-id's between multiple apps that talk to each other via SQS. It looks like this library will automatically generate a subsegment for talking to SQS, but there's nothing on the other end (say in MessageAttributes) to know the traceId and parentId of that subsegment. Is there something I'm missing? For now, we are just adding it to the MessageBody but this means I can't use this library to instrument AWS clients, as I need to know the subsegment id.

I found this link referencing a "convention" to use MessageAttributes: https://forums.aws.amazon.com/thread.jspa?messageID=794108 but it doesn't look like this library does it.

**Comment by haotianw465** [comment]
Hi,

We have an item in our back log to have the X-Ray SDK automatically construct trace header and put it in the SQS message metadata on the sender side and extract this trace header from receiver side. Please stay tuned.

In the meantime you can construct a trace header yourself following the format here: https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader and add it to your message attribute. I agree this is not ideal but this at least can bridge the gap between the producer and consumer and the actually message processing time and trace id propagation is probably more useful than SQS client API call. Please let me know if this workaround is usable in your use case.

**Comment by mattcasey** [comment]
Thanks for a fast response! I am OK doing it myself for now -- My hope is to line up as closely as possible with what the end result will be, ideally something that is supported in the Java SDK as well.

I'm unclear what you mean by the "message metadata" -- I see that in aws_p.js, you are already adding an http header with the trace id but still create a subsegment, and I didn't notice any additional segments/subsegments created by SQS, so I'm guessing that this is not necessary for SQS clients. For now, I am adding properties in the MessageAttributes for "Root" and "Parent" and reading them on the client side. Another option for us would be to add the parent and trace id's to the MessageBody, but that only works in cases where we are stringifying JSON.

So, in the meantime I'm just wondering what you'd recommend as best practice? Is MessageAttributes a good place to put it?

**Comment by mattcasey** [comment]
Thanks! i'll close this issue for now
