### ISSUE TITLE
[Lambda] new Segment does not appear when using facade as parent

### ISSUE THREAD

**Issue by bryanvaz** [aws/aws-xray-sdk-node#379]
I'm trying to set the `addIncomingRequestData` in Lambda. Using this function on the facade `Segment` does not work, and X-Ray just seems to ignore the additional data:
```js
// Koa middleware
const koaMw = async (ctx, next) => {
  const parent = AWSXRay.getSegment(); // returns the Lambda facade segment
  const segment = parent.addNewSubsegment('Koa');
  parent.addIncomingRequestData(new IncomingRequestData(ctx.req));
  await next(); // Continue Koa request execution
  segment.close();
  parent.http.close();
  // ... Lambda will close the facade segment, so don't worry
}
```
<img width="1103" alt="Screen Shot 2021-02-24 at 3 13 15 PM" src="https://user-images.githubusercontent.com/9157498/109060050-ec8f4280-76b2-11eb-9004-3b49215286a5.png">

As an alternative, I thought that if I created a new `Segment` and using Lambda's facade `Segment`'s `trace_id` as the `parent` for the new `Segment` I could get it to work. Based on the X-Ray docs, I would expect this to create a new node on the service map that would be downstream from the lambda execution. This was even worse because X-Ray just ignored my new Segment completely.

```js
// Koa middleware
const koaMw = async (ctx, next) => {
  const parent = AWSXRay.getSegment(); // returns the Lambda facade segment

  const amznTraceHeader = mwUtils.processHeaders(ctx);
  const segment = new Segment(
      'Koa',
      amznTraceHeader.Root || amznTraceHeader.root,
      parent.trace_id,
    );
  mwUtils.resolveSampling(amznTraceHeader, segment, ctx);
  segment.addIncomingRequestData(new IncomingRequestData(ctx.req));
  await next(); // Continue Koa request execution
  segment.http.close();
  segment.close();
  segment.flush();
  // ... Lambda will close the facade segment, so don't worry
}
```
<img width="1099" alt="Screen Shot 2021-02-24 at 3 17 37 PM" src="https://user-images.githubusercontent.com/9157498/109060495-750de300-76b3-11eb-9da8-578863f0ea34.png">

Is there anyway to create a new downstream service `Segment` on service map, separate from the Lambda node?
_(I need some way to capture the HTTP request details because HTTP API Gateways do not support X-Ray)_

Cheers,
Bryan

**Comment by bhautikpip** [comment]
Hi Bryan,

I think as [reference](https://github.com/awsdocs/aws-lambda-developer-guide/pull/170/files) from here, I believe segments created within lambda function are treated as facade segments hence no operation could be performed using that segment. I believe when you call `parent.addIncomingRequestData(new IncomingRequestData(ctx.req));` from within your lambda function SDK treats that function call as no-op. https://github.com/aws/aws-xray-sdk-node/blob/c3e7b859b4c6e223c568dc4f7a3a54848625df19/packages/core/lib/segments/segment.d.ts#L17 As per your original question this [answer](https://github.com/aws/aws-xray-sdk-node/issues/45#issuecomment-593704006) would explain better on having separate nodes on X-Ray console when you create segment within your lambda function.

**Comment by bryanvaz** [comment]
@bhautikpip Yes, I'm aware of the no-op. that's why I thought using the facade as a parent and creating a new `Segment` would work.
Specifying the lambda facade as a parent should theoretically work, because it is the same thing that happens when you create a sub request to another service. In that scenario, the second service would use the lambda facade `trace_id` as the parent in order connect it to the same service graph.

As a note, if you create a new `Segment` without a parent, the node will show up, but without any relation to the lambda initialization and invocation node, which makes the waterfall kind of useless.

**Comment by bhautikpip** [comment]
right. I think as per my understanding this case would be similar as having Express server deployed to lambda and Express middleware tries to create segment but Lambda facade segment will ignore that and on the X-Ray console you will only see one node `AWS::Lambda::Function` as being discussed here https://github.com/aws/aws-xray-sdk-node/issues/45
