### ISSUE TITLE
RDS Data Service appears as an unlabed HTTP endpoint

### ISSUE THREAD

**Issue by thuringia** [aws/aws-xray-sdk-node#391]
It looks like the X-Ray SDK needs some special support for RDS Data Service.

Currently we're capturing the complete AWS SDK as well as `http`/`http2`/`https` for REST requests but the RDS Data Service appears as an unlabeled HTTP node, not a RDS node.

**Comment by willarmiros** [comment]
Hello,

Can you provide a sample snippet of how you're calling RDS? Also a screenshot or raw trace data would be helpful to see exactly what is being recorded.

**Comment by thuringia** [comment]
Hi,
this is how we configure X-Ray in a shared module:
```typescript
if (currentConfig().tracing) {
  AWSXRay = require("aws-xray-sdk");
  invariant(AWSXRay, "Failed to load XRay");
  AWS = AWSXRay.captureAWS(require("aws-sdk"));
  PG = AWSXRay.capturePostgres(require("pg"));
  AWSXRay.capturePromise();
  AWSXRay.captureHTTPsGlobal(require("http"), true);
  AWSXRay.captureHTTPsGlobal(require("https"), true);
  AWSXRay.captureHTTPsGlobal(require("http2"), true);
}
```
the patched SDKs and libraries are then exported for lamda handlers et cetera.
The handler in question uses RDS Data Service like so (`aws` being the patched AWS SDK):

```typescript
import { aws } from "../utils/aws";

/* omitted for brevity */

const ds = new aws.RDSDataService();
ds
  .executeStatement(params)
  .promise()
  .then(() => metrics.putMetric("EventsSuccessful", 1));
```

This is what we see in X-Ray Service Lens:
![image](https://user-images.githubusercontent.com/752104/111993371-d7250100-8b16-11eb-904e-c23f32d0ab94.png)
![image](https://user-images.githubusercontent.com/752104/111998055-ef4b4f00-8b1b-11eb-8dc5-b1bee69330b9.png)

an this is the raw tracing data:
<details>
<summary>raw tracing data</summary>
<pre>
{
    "Id": "1-60589d57-29478fadae6bbc139e74b16e",
    "Duration": 0.283,
    "LimitExceeded": false,
    "Segments": [
        {
            "Id": "2cde107ecbea9a35",
            "Document": {
                "id": "2cde107ecbea9a35",
                "name": "tiffany-nonlive-consumeFromBI",
                "start_time": 1616420183.241,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.524,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "request_id": "bac7804b-2e52-4718-97c1-b5d535526874"
                },
                "origin": "AWS::Lambda",
                "resource_arn": "arn:aws:lambda:eu-central-1:897104064270:function:tiffany-nonlive-consumeFromBI",
                "subsegments": [
                    {
                        "id": "018664910b91adf2",
                        "name": "Attempt #1",
                        "start_time": 1616420183.241,
                        "end_time": 1616420183.524,
                        "http": {
                            "response": {
                                "status": 200
                            }
                        }
                    }
                ]
            }
        },
        {
            "Id": "43371e1a35efac80",
            "Document": {
                "id": "43371e1a35efac80",
                "name": "tiffany-nonlive-consumeFromBI",
                "start_time": 1616420183.2501652,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.5219874,
                "parent_id": "018664910b91adf2",
                "aws": {
                    "account_id": "897104064270",
                    "function_arn": "arn:aws:lambda:eu-central-1:897104064270:function:tiffany-nonlive-consumeFromBI",
                    "resource_names": [
                        "tiffany-nonlive-consumeFromBI"
                    ]
                },
                "origin": "AWS::Lambda::Function",
                "subsegments": [
                    {
                        "id": "2768cc5cfc55cdd6",
                        "name": "Invocation",
                        "start_time": 1616420183.250213,
                        "end_time": 1616420183.521597,
                        "aws": {
                            "function_arn": "arn:aws:lambda:eu-central-1:897104064270:function:tiffany-nonlive-consumeFromBI"
                        },
                        "subsegments": [
                            {
                                "id": "d87d9777450b3590",
                                "name": "rdsdataservice",
                                "start_time": 1616420183.251,
                                "end_time": 1616420183.282,
                                "http": {
                                    "response": {
                                        "status": 200
                                    }
                                },
                                "aws": {
                                    "retries": 0,
                                    "region": "eu-central-1",
                                    "operation": "ExecuteStatement",
                                    "request_id": "f307f4d2-070d-43be-acd7-f28c456f002f"
                                },
                                "namespace": "aws"
                            },
                            {
                                "id": "8574e00645fc7720",
                                "name": "rdsdataservice",
                                "start_time": 1616420183.283,
                                "end_time": 1616420183.318,
                                "http": {
                                    "response": {
                                        "status": 200
                                    }
                                },
                                "aws": {
                                    "retries": 0,
                                    "region": "eu-central-1",
                                    "operation": "ExecuteStatement",
                                    "request_id": "7920f554-76ae-46c5-9470-788994ed56a6"
                                },
                                "namespace": "aws"
                            },
                            {
                                "id": "4a701a17c2babc90",
                                "name": "rdsdataservice",
                                "start_time": 1616420183.319,
                                "end_time": 1616420183.337,
                                "http": {
                                    "response": {
                                        "status": 200
                                    }
                                },
                                "aws": {
                                    "retries": 0,
                                    "region": "eu-central-1",
                                    "operation": "ExecuteStatement",
                                    "request_id": "5736eb86-4a70-48eb-9d04-2684e33c29c8"
                                },
                                "namespace": "aws"
                            },
                            {
                                "id": "fd6c7b8a1ba5f0ef",
                                "name": "rdsdataservice",
                                "start_time": 1616420183.338,
                                "end_time": 1616420183.355,
                                "http": {
                                    "response": {
                                        "status": 200
                                    }
                                },
                                "aws": {
                                    "retries": 0,
                                    "region": "eu-central-1",
                                    "operation": "ExecuteStatement",
                                    "request_id": "4daf35ad-fb78-4086-a227-25f4c5a80821"
                                },
                                "namespace": "aws"
                            },
                            {
                                "id": "9f9a5f6369e7ff1e",
                                "name": "rdsdataservice",
                                "start_time": 1616420183.356,
                                "end_time": 1616420183.381,
                                "http": {
                                    "response": {
                                        "status": 200
                                    }
                                },
                                "aws": {
                                    "retries": 0,
                                    "region": "eu-central-1",
                                    "operation": "ExecuteStatement",
                                    "request_id": "7290657e-dd0f-4387-a4f4-3402b13fca16"
                                },
                                "namespace": "aws"
                            },
                            {
                                "id": "f94d3590e0e983ae",
                                "name": "rdsdataservice",
                                "start_time": 1616420183.382,
                                "end_time": 1616420183.419,
                                "http": {
                                    "response": {
                                        "status": 200
                                    }
                                },
                                "aws": {
                                    "retries": 0,
                                    "region": "eu-central-1",
                                    "operation": "ExecuteStatement",
                                    "request_id": "2b16c4cc-f531-4d8c-b770-3621e6666a3e"
                                },
                                "namespace": "aws"
                            },
                            {
                                "id": "fbcb8ff74fcacafe",
                                "name": "rdsdataservice",
                                "start_time": 1616420183.42,
                                "end_time": 1616420183.438,
                                "http": {
                                    "response": {
                                        "status": 200
                                    }
                                },
                                "aws": {
                                    "retries": 0,
                                    "region": "eu-central-1",
                                    "operation": "ExecuteStatement",
                                    "request_id": "e21e3820-d08e-4488-ae10-460b6ea1a108"
                                },
                                "namespace": "aws"
                            },
                            {
                                "id": "a514ed4cf944139f",
                                "name": "rdsdataservice",
                                "start_time": 1616420183.439,
                                "end_time": 1616420183.477,
                                "http": {
                                    "response": {
                                        "status": 200
                                    }
                                },
                                "aws": {
                                    "retries": 0,
                                    "region": "eu-central-1",
                                    "operation": "ExecuteStatement",
                                    "request_id": "f1ab615c-92b0-42bc-9efe-1f455c85b497"
                                },
                                "namespace": "aws"
                            },
                            {
                                "id": "49f1b6f801d2559c",
                                "name": "rdsdataservice",
                                "start_time": 1616420183.478,
                                "end_time": 1616420183.494,
                                "http": {
                                    "response": {
                                        "status": 200
                                    }
                                },
                                "aws": {
                                    "retries": 0,
                                    "region": "eu-central-1",
                                    "operation": "ExecuteStatement",
                                    "request_id": "a4bfa655-388e-4b3e-995a-7ed3181da603"
                                },
                                "namespace": "aws"
                            },
                            {
                                "id": "2c105f84646de4be",
                                "name": "rdsdataservice",
                                "start_time": 1616420183.495,
                                "end_time": 1616420183.517,
                                "http": {
                                    "response": {
                                        "status": 200
                                    }
                                },
                                "aws": {
                                    "retries": 0,
                                    "region": "eu-central-1",
                                    "operation": "ExecuteStatement",
                                    "request_id": "5666f812-2137-4733-970a-0d393fa9d8cd"
                                },
                                "namespace": "aws"
                            }
                        ]
                    },
                    {
                        "id": "deb960cce2d9cc85",
                        "name": "Overhead",
                        "start_time": 1616420183.5216308,
                        "end_time": 1616420183.5218713,
                        "aws": {
                            "function_arn": "arn:aws:lambda:eu-central-1:897104064270:function:tiffany-nonlive-consumeFromBI"
                        }
                    }
                ]
            }
        },
        {
            "Id": "05d72de011dc3e0f",
            "Document": {
                "id": "05d72de011dc3e0f",
                "name": "rdsdataservice",
                "start_time": 1616420183.382,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.419,
                "parent_id": "f94d3590e0e983ae",
                "inferred": true,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "retries": 0,
                    "region": "eu-central-1",
                    "operation": "ExecuteStatement",
                    "request_id": "2b16c4cc-f531-4d8c-b770-3621e6666a3e"
                },
                "origin": "AWS::rdsdataservice"
            }
        },
        {
            "Id": "28519a4d383a492a",
            "Document": {
                "id": "28519a4d383a492a",
                "name": "rdsdataservice",
                "start_time": 1616420183.495,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.517,
                "parent_id": "2c105f84646de4be",
                "inferred": true,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "retries": 0,
                    "region": "eu-central-1",
                    "operation": "ExecuteStatement",
                    "request_id": "5666f812-2137-4733-970a-0d393fa9d8cd"
                },
                "origin": "AWS::rdsdataservice"
            }
        },
        {
            "Id": "156fc8e229923af2",
            "Document": {
                "id": "156fc8e229923af2",
                "name": "rdsdataservice",
                "start_time": 1616420183.356,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.381,
                "parent_id": "9f9a5f6369e7ff1e",
                "inferred": true,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "retries": 0,
                    "region": "eu-central-1",
                    "operation": "ExecuteStatement",
                    "request_id": "7290657e-dd0f-4387-a4f4-3402b13fca16"
                },
                "origin": "AWS::rdsdataservice"
            }
        },
        {
            "Id": "0af56f8f2370e7b3",
            "Document": {
                "id": "0af56f8f2370e7b3",
                "name": "rdsdataservice",
                "start_time": 1616420183.251,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.282,
                "parent_id": "d87d9777450b3590",
                "inferred": true,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "retries": 0,
                    "region": "eu-central-1",
                    "operation": "ExecuteStatement",
                    "request_id": "f307f4d2-070d-43be-acd7-f28c456f002f"
                },
                "origin": "AWS::rdsdataservice"
            }
        },
        {
            "Id": "3df141ed04cd0b42",
            "Document": {
                "id": "3df141ed04cd0b42",
                "name": "rdsdataservice",
                "start_time": 1616420183.42,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.438,
                "parent_id": "fbcb8ff74fcacafe",
                "inferred": true,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "retries": 0,
                    "region": "eu-central-1",
                    "operation": "ExecuteStatement",
                    "request_id": "e21e3820-d08e-4488-ae10-460b6ea1a108"
                },
                "origin": "AWS::rdsdataservice"
            }
        },
        {
            "Id": "2846fc761dbeed4e",
            "Document": {
                "id": "2846fc761dbeed4e",
                "name": "rdsdataservice",
                "start_time": 1616420183.283,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.318,
                "parent_id": "8574e00645fc7720",
                "inferred": true,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "retries": 0,
                    "region": "eu-central-1",
                    "operation": "ExecuteStatement",
                    "request_id": "7920f554-76ae-46c5-9470-788994ed56a6"
                },
                "origin": "AWS::rdsdataservice"
            }
        },
        {
            "Id": "273e22212c958574",
            "Document": {
                "id": "273e22212c958574",
                "name": "rdsdataservice",
                "start_time": 1616420183.319,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.337,
                "parent_id": "4a701a17c2babc90",
                "inferred": true,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "retries": 0,
                    "region": "eu-central-1",
                    "operation": "ExecuteStatement",
                    "request_id": "5736eb86-4a70-48eb-9d04-2684e33c29c8"
                },
                "origin": "AWS::rdsdataservice"
            }
        },
        {
            "Id": "277a798101b62257",
            "Document": {
                "id": "277a798101b62257",
                "name": "rdsdataservice",
                "start_time": 1616420183.338,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.355,
                "parent_id": "fd6c7b8a1ba5f0ef",
                "inferred": true,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "retries": 0,
                    "region": "eu-central-1",
                    "operation": "ExecuteStatement",
                    "request_id": "4daf35ad-fb78-4086-a227-25f4c5a80821"
                },
                "origin": "AWS::rdsdataservice"
            }
        },
        {
            "Id": "23b1db15335d1b02",
            "Document": {
                "id": "23b1db15335d1b02",
                "name": "rdsdataservice",
                "start_time": 1616420183.439,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.477,
                "parent_id": "a514ed4cf944139f",
                "inferred": true,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "retries": 0,
                    "region": "eu-central-1",
                    "operation": "ExecuteStatement",
                    "request_id": "f1ab615c-92b0-42bc-9efe-1f455c85b497"
                },
                "origin": "AWS::rdsdataservice"
            }
        },
        {
            "Id": "133c865f3dc269a8",
            "Document": {
                "id": "133c865f3dc269a8",
                "name": "rdsdataservice",
                "start_time": 1616420183.478,
                "trace_id": "1-60589d57-29478fadae6bbc139e74b16e",
                "end_time": 1616420183.494,
                "parent_id": "49f1b6f801d2559c",
                "inferred": true,
                "http": {
                    "response": {
                        "status": 200
                    }
                },
                "aws": {
                    "retries": 0,
                    "region": "eu-central-1",
                    "operation": "ExecuteStatement",
                    "request_id": "a4bfa655-388e-4b3e-995a-7ed3181da603"
                },
                "origin": "AWS::rdsdataservice"
            }
        }
    ]
}
</pre>
</details>

Based on how the data is visualized, I'm not sure if this is a data capturing issue, or an issue within X-Ray itself.
Any help is greatly appreciated

**Comment by willarmiros** [comment]
This is the expected behavior when calling the RDS service. Specifically, taking this subsegment as an example:

```
{
                                "id": "d87d9777450b3590",
                                "name": "rdsdataservice",
                                "start_time": 1616420183.251,
                                "end_time": 1616420183.282,
                                "http": {
                                    "response": {
                                        "status": 200
                                    }
                                },
                                "aws": {
                                    "retries": 0,
                                    "region": "eu-central-1",
                                    "operation": "ExecuteStatement",
                                    "request_id": "f307f4d2-070d-43be-acd7-f28c456f002f"
                                },
                                "namespace": "aws"
                            },
```

You can see that it has the `aws` namespace, which indicates it is being captured by the X-Ray SDK as an AWS SDK service node (which is expected), not a HTTP node. The node on ServiceLens is labelled as the AWS Service that is being called. This is the behavior for all AWS Services called using the AWS SDK, with a few exceptions like DynamoDB and S3 where we have special-cased integrations to label nodes based on particular tables or buckets being targeted. Were you expecting for the node to be labelled with the DB name or something similar?

**Comment by thuringia** [comment]
I was expecting RDS Data Service to show the same level of integration as regular queries to RDS via a Postgres or MySQL connection, in that sense, yes I was expecting data like a table name to be shown. 
To be perfectly honest, I was expecting at least the same level of integration as with S3 or DynamoDB...
