### ISSUE TITLE
Can haz release?

### ISSUE THREAD

**Issue by isaacl** [aws/aws-xray-sdk-node#394]
Is there a timeline for the next release?

**Comment by willarmiros** [comment]
Sorry again for the delay here - it has been blocked by several re-prioritizations recently. We are actively working on improving automations to avoid this and to get the next release out the door as soon as possible. I am unable to give an exact ETA.

**Comment by deel77** [comment]
Is there any new info about new release ETA. As I see prepare for 3.3.0 merged.

We would need mostly AWS SDKv3 support. Thanks.

**Comment by willarmiros** [comment]
Can haz release.
