### ISSUE TITLE
How to get trace_id to configure cloudwatch logs correlation

### ISSUE THREAD

**Issue by organic-scholar** [aws/aws-xray-sdk-node#408]
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy_servicelens_CloudWatch_agent_logintegration.html

It is already supported by java SDK to simulate the same behavior in nodejs with my log function  I need to inject trace_id  into the log message. What is the most appropriate way to get trace_id?

**Comment by willarmiros** [comment]
Use: `AWSXRay.getSegment().trace_id` while a segment is in progress.

https://github.com/aws/aws-xray-sdk-node/blob/2c4459a0ea06912259bd627d34cb99e46878538f/packages/core/lib/segments/segment.d.ts#L10
