### ISSUE TITLE
Preserve tracing using sqs-consumer.

### ISSUE THREAD

**Issue by hariharasudhan-nineleaps** [aws/aws-xray-sdk-node#419]
I have two microservices namely `user-service` and `notification-service`, whenever user sign-up to `user-service`. the message will add to sqs queue with `AWSTraceHeader`, now from `notification-service` [sqs-consumer](https://www.npmjs.com/package/sqs-consumer) will poll and pass that message  to handleMessage callback function and send an email to enduser using SES.

I can able to trace the process till, `user-service ---> sqs` queue, but how can traceId entire flow like `user-service->queue->notification-service->ses`. I tried the following code

```
handleMessage: async (message: SQS.Message) => {
    const segment = AWSXRay.getSegment()
    if(segment){
      segment.trace_id = message.Attributes?.AWSTraceHeader
    }
    
    await wiring.sqsService.handleMessage(message);
  }
```

 but got the error like below
`Property 'trace_id' does not exist on type 'Segment | Subsegment'.
  Property 'trace_id' does not exist on type 'Subsegment'.`

How can I trace the entire process?

**Comment by hariharasudhan-nineleaps** [comment]
Thanks for your reply, one small question, if I close the segment after handleMessage like below

```
handleMessage: async (message: SQS.Message) => {
    const segment = AWSXRay.getSegment()
    if(segment){
      segment.trace_id = message.Attributes?.AWSTraceHeader
    }
    
    await wiring.sqsService.handleMessage(message);
    segment.closeSegment()
  }
```

Do I need to open the new segment again, because `openSegment()` invoked like below.

```
const segment = new AWSXRay.Segment(this.appName);
    const ns = AWSXRay.getNamespace();
    ns.run(() => {
      AWSXRay.setSegment(segment);
      this.sqsConsumer.start();
    });
```

**Comment by willarmiros** [comment]
@hariharasudhan-nineleaps I'm not sure I entirely understand your question. Each call to open a segment should have a corresponding call to close the segment later in execution, no matter what (e.g. in a `finally` block).
