### ISSUE TITLE
Smoke tests failing

### ISSUE THREAD

**Issue by afloyd** [aws/aws-xray-sdk-node#426]
https://github.com/aws/aws-xray-sdk-node/actions/runs/837434366

**Comment by lupengamzn** [comment]
Hey @afloyd ,

The new releases `v3.3.3` are out, which fixed the issue in https://github.com/aws/aws-xray-sdk-node/issues/427:

https://www.npmjs.com/package/aws-xray-sdk-core/v/3.3.3
https://www.npmjs.com/package/aws-xray-sdk-express/v/3.3.3
https://www.npmjs.com/package/aws-xray-sdk-mysql/v/3.3.3
https://www.npmjs.com/package/aws-xray-sdk-postgres/v/3.3.3
https://www.npmjs.com/package/aws-xray-sdk/v/3.3.3
https://www.npmjs.com/package/aws-xray-sdk-koa2/v/3.3.3
https://www.npmjs.com/package/aws-xray-sdk-hapi/v/3.3.3
https://www.npmjs.com/package/aws-xray-sdk-restify/v/3.3.3

The smoke tests now have passed: https://github.com/aws/aws-xray-sdk-node/actions/runs/839780848
