### ISSUE TITLE
Cannot find module 'aws-xray-sdk-core/lib/middleware/sampling/service_connector' from 'node_modules/aws-xray-sdk-express/lib/express_mw.js'

### ISSUE THREAD

**Issue by ls-jacob-lawrence** [aws/aws-xray-sdk-node#427]
`Cannot find module 'aws-xray-sdk-core/lib/middleware/sampling/service_connector' from 'node_modules/aws-xray-sdk-express/lib/express_mw.js'`

Version 3.3.2 introduces this bug due to 84e65c3f2c9119a40f88c5e6ea1d9070a0a8ca7f

The absolute path is missing the /dist/ for consumers

**Comment by ChungminPark** [comment]
I had an issue derived from the new /dist/ path behind the /lib/ because I directed accessed to `aws-xray-sdk-core/lib/context_utils` on my project. so I got `Cannot find module 'aws-xray-sdk-core/lib/context_utils` error. I solved this issue by fixing `aws-xray-sdk-core` version to downgraded one("aws-xray-sdk-core": "^3.1.0" -> "aws-xray-sdk-core": "3.3.1" on package.json).

**Comment by estiller** [comment]
This happened to our team as well. All newly built Docker images stopped loading. We worked around it by setting the version to exactly "3.3.1" on package.json.

**Comment by padzikm** [comment]
We have the same problem with error Runtime.ImportModuleError: Error: Cannot find module 'aws-xray-sdk-core/lib/middleware/sampling/service_connector' - version 3.2.0 all packages aws-xray-sdk-*

**Comment by willarmiros** [comment]
Hello,

Thanks for raising this issue. We'll get a patch out ASAP to address it.

**Comment by willarmiros** [comment]
@ChungminPark we intend on keeping the new structure with `dist` in the path. All of the public APIs in the `context_utils` module are exposed via the top-level `AWSXRay` object, e.g. `AWSXRay.setSegment()`, and I would recommend referencing them like that so you aren't dependent on the directory structure.

**Comment by GregTurner** [comment]
Can we get a npm publish please?

**Comment by willarmiros** [comment]
@GregTurner preparing the release right now.

**Comment by willarmiros** [comment]
This issue is fixed in v3.3.3, available now on NPM. Please let us know if there are any further issues. Apologies again for the trouble.

**Comment by ChungminPark** [comment]
@willarmiros Thanks a lot!
