### ISSUE TITLE
How to instrument express middleware with next & return

### ISSUE THREAD

**Issue by mattfysh** [aws/aws-xray-sdk-node#453]
Given the following middleware:

```js
const authMW = async (req, res, next) => {
  const auth = await lengthyAuthFunction(...)
  if (!auth) return res.sendStatus(401)
  // ... more async code
  next()
}
```

How would you go about instrumenting this segment, given that the function will either (1) return early; or (2) not return anything, and calls `next()` once done?

I tried wrapping the middleware and waiting until the async function completed before calling `subsegment.close()`, but the problem is that `next()` is invoked _before_ the async function completes and can cause nested segments where there should be siblings.

**Comment by mattfysh** [comment]
I've also tried this, with no luck:

```js
const doAuthMW = async (req, res) => {
  const auth = await lengthyAuthFunction(...)
  if (!auth) return res.sendStatus(401)
  // ... more async code
}

export const authMW = (req, res, next) => {
  AWXRay.captureAsyncFunc('Auth', async subsegment => {
    let err
    try {
      await doAuthMW(req, res)
    } catch (e) {
      subsegment.addAnnotation('didError', true)
      subsegment.addMetadata('error', e.message)
      err = e
    }
    subsegment.close()
    next(err)
  }
}
```

Still getting the subsegments created inside `next` coming up as children of 'Auth' ... even though that subsegment has already been closed prior to calling `next()`

**Comment by mattfysh** [comment]
Ok this seems to work, by moving the call to `next` to be outside `captureAsyncFunc`... even though the subsegment was already closed:

```js
export const authMW = async (req, res, next) => {
  let err
  await AWXRay.captureAsyncFunc('Auth', async subsegment => {
    try {
      await doAuthMW(req, res)
    } catch (e) {
      subsegment.addAnnotation('didError', true)
      subsegment.addMetadata('error', e.message)
      err = e
    }
    subsegment.close()
  }
  next(err)
}
```

**Comment by willarmiros** [comment]
@mattfysh sorry for the delayed response - that is the approach I'd recommend for your use case. Even though you manually close the subsegment, it is still set in the context as long as you're in the `captureAsyncFunc` closure, hence why you saw them as children.
