### ISSUE TITLE
Error: No context available. ns.run() or ns.bind() must be called first. NestJS

### ISSUE THREAD

**Issue by akash19980** [aws/aws-xray-sdk-node#454]
I am getting No context available at setSegement(). I am using Nest Js framework 
```
const AWSXRay = require('aws-xray-sdk');
const AWS = AWSXRay.captureAWS(require('aws-sdk'));
AWSXRay.captureHTTPsGlobal(require('https'));
 seg = new AWSXRay.Segment('aws-Xray');
    AWSXRay.setSegment(seg);
    seg.addAnnotation('functionName', 'mainFunction');
    console.log(seg);
```

**Comment by willarmiros** [comment]
As the error message indicates, you must call `setSegment` within a `ns.run()` or `ns.bind()` closure. For example see: https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#developing-custom-solutions-without-middleware
