### ISSUE TITLE
Incompatible with Winston v3.0

### ISSUE THREAD

**Issue by IllegalCactus** [aws/aws-xray-sdk-node#48]
Using the SDK with Winston v.3.0.0 produces the following error:

```
node_modules/aws-xray-sdk-core/lib/logger.js:17
    logger = new (winston.Logger)({});

TypeError: winston.Logger is not a constructor
```

Winston had a breaking change in 3.0 which changes how the logger should be constructed:

https://github.com/winstonjs/winston#creating-your-own-logger

https://github.com/winstonjs/winston/commit/eff6f00588ea6e7fcfc0a33bcf049ad85c76b6d9#diff-fc1a687308b45c41cf7efa7aff4253dd

Not sure if updating the Winston version in this project is an option?

**Comment by awssandra** [comment]
Hi Cactus,

We're planning on removing Winston - see https://github.com/aws/aws-xray-sdk-node/issues/10. However, in the mean time, if you'd like to submit a PR with a bump to 3.0 we'd be happy to review it.

Is there any particular reason you're wanting to use the SDK with Winston 3?

**Comment by IllegalCactus** [comment]
Ah I didn't see that issue, thanks. In that case, I'm happy to close this as I don't have an urgent need to use 3.0 in the meantime. I just spotted this error while upgrading some dependencies in a project but in my case I can stick with 2.x too.
