### ISSUE TITLE
Capture S3 getSignedUrl does not work with AWS SDK Instrumentation

### ISSUE THREAD

**Issue by MartinLoeper** [aws/aws-xray-sdk-node#49]
### Example
I use the following typescript code in our nodejs backend server:

```js
import * as AWSWithoutXRayWrapper from "aws-sdk";
import * as AWSXRay from "aws-xray-sdk";
const AWS = AWSXRay.captureAWS(AWSWithoutXRayWrapper);
[...]
return new Promise((resolve, reject) => {
  [...]
  this.client.upload(settings as any, (err, data) => {
    if (err) {
        reject(ApiError.AwsUploadError(err));
    } else {
        const expirationSeconds = Math.floor((expirationDate.getTime() - new Date().getTime()) / 1000);
        const params = { Bucket: data.Bucket, Key: data.Key, Expires: expirationSeconds };

        // we must wrap calls to aws api which depend on another async function
        AWSXRay.captureAsyncFunc("SignS3Url", (subsegment) => {
            this.client.getSignedUrl("getObject", params, (error, url) => {
                if (err) {
                    reject(ApiError.AwsUploadError(err));
                 } else {
                    resolve(url);
                 }

                 if (subsegment) {
                    subsegment.close();
                 }
            });
        });
    }
 });
});
```

### Issue
This code prevents `flush()` to be called on the segment which was created by xray-express.
I debugged the file [aws_p.js](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/patchers/aws_p.js) and found out that the S3 client calls `build` when making the `presign` request, but never calls `complete` on that request.   
Thus, the subsegment is never closed and the corresponding segment never flushed.

Could someone please look into this and tell me what is happening here? =)

**Comment by billnbell** [comment]
It would be fantastic if XRAY supported async await, and this code could be MUCH simpler.

**Comment by MartinLoeper** [comment]
@billnbell Yes that's true. We patched the SDK in our project by using cls-hooked instead of continuation-local-storage. However that is not convenient and makes updating the SDK difficult.

@all I provided the following workaround for the given code:
```js
[...]
if (subsegment) {
  subsegment.decrementCounter();
  subsegment.close();
}
[...]
```

This makes the getSignedUrl call work as expected and the request is sent to the xray daemon.

**Comment by haotianw465** [comment]
Thank you for reporting the issue. We will look into a fix soon.
