### ISSUE TITLE
Traces from Lambda to StepFunction to Lambda

### ISSUE THREAD

**Issue by vchittar** [aws/aws-xray-sdk-node#497]
Hi, 

I am trying to trace my functions going from a step function to a lambda to a step function. 

Currently my trace map looks something like this: 

Trace 1: Lambda to Step Function
Trace 2: Step Function to Lambda

Ideally I would like to have: 
Lambda -> Step Function -> Lambda 
All wrapped around one trace. 

Is that possible to do? 

Thanks.

**Comment by wangzlei** [comment]
Yes, please make sure enable both xray tracing in you Lambda and Step function.

**Comment by vchittar** [comment]
I have, but the traces are still not connected to each other. We are still getting them in two different traces. We are able to see connected traces from step function to lambda but not lambda to step function.

**Comment by wangzlei** [comment]
Could you instrument the first Lambda function by https://github.com/aws-observability/aws-otel-lambda

**Comment by vchittar** [comment]
I dont believe I can use that, since our company operates within a closed firewall and any unapproved modules would require prior approval. Or is this natively available?

**Comment by wangzlei** [comment]
propagate trace context from the first Lambda to StepFunction, to connect the trace between the first Lambda and stepfunction.

**Comment by carolabadeer** [comment]
Closing as stale issue - please reopen if there are any further questions
