### ISSUE TITLE
Configure captureHttps behaviour

### ISSUE THREAD

**Issue by chrismatheson** [aws/aws-xray-sdk-node#506]
currently the default captureHttps behaviour treats 404 responses as errors. In my particular use case 404 is an acceptable response so these errors are essentially false positives.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/420915/167111648-4a1e1997-0537-43e2-9af1-124c6157b0c5.png">

it there a way to configure the behaviour in this case? or possibly to opt out of generic X-ray behaviour for the particular call and instrument manually?

**Comment by wangzlei** [comment]
In xray http instrument we hardcode 404 status code as error as a generic requirement, it is not configurable.
as a workaround, you can maintain your custom logic by overriding https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/utils.js#L18

**Comment by carolabadeer** [comment]
Closing as stale issue - please reopen if there are any further questions
