### ISSUE TITLE
False positive critical vulnerabilities reported when packaging aws-xray-sdk in a container

### ISSUE THREAD

**Issue by gbvanrenswoude** [aws/aws-xray-sdk-node#507]
When using `"aws-xray-sdk": "^3.3.4",` (we have 3.3.5) in a Docker Image, ECR Container scanning reports 6 Critical security vulnerabilities, on lodash, minimist and jsonpointer. This can be traced back to a `yarn.lock` file (https://github.com/Jeff-Lewis/async-hook-jl/blob/master/yarn.lock) committed and downloaded onto the fs.

```sh
`-- aws-xray-sdk@3.3.5
  `-- aws-xray-sdk-core@3.3.5
    `-- cls-hooked@4.2.2
      `-- async-hook-jl@1.7.6
```

ECR Enhanced Scanning triggers on .lock files and reports on the content.

**Comment by wangzlei** [comment]
link to the similar issue before: https://github.com/aws/aws-xray-sdk-node/issues/492

**Comment by carolabadeer** [comment]
Closing as related issue #492 has been resolved.
