### ISSUE TITLE
Typescript definitions of TraceId doesnt match

### ISSUE THREAD

**Issue by WtfJoke** [aws/aws-xray-sdk-node#519]
Since https://github.com/aws/aws-xray-sdk-node/pull/361 the [typings](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/segments/attributes/trace_id.d.ts) of [TraceId](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/segments/attributes/trace_id.js) doesnt seem match with the constructor definition.

The constructor declares two optional string parameters (`tsHex` and `numberHex`), where as the types says there is no parameter.

If needed, we can also provide a PR

**Comment by carolabadeer** [comment]
Resolved with PR #520 mentioned above
