### ISSUE TITLE
XRay KOA Library OpenSegment() function type issue in TypeScript

### ISSUE THREAD

**Issue by blam135** [aws/aws-xray-sdk-node#522]
Hi there,

I noticed that for the XRay Koa Lib, when injecting the `openSegment` function middleware into a Koa app, it throws a type error in the first screenshot when I do the same thing in a TS file as mentioned in the README. 

But after a while digging into it, I realised I needed to type it as `Koa.Middleware` as shown in the second screenshot. Is it possible we could type this as `Koa.Middleware` to prevent the need to do `app.use(XRayKOA.openSegment('segment') as Koa.Middleware)` or update the README to make it clear that this is what should be done on a TS file? 

Many thanks :) 

![image](https://user-images.githubusercontent.com/41976995/181249891-bde8b20c-7e7e-472b-b3a4-114045d7fe3a.png)

![image](https://user-images.githubusercontent.com/41976995/181250656-b2adb287-0838-41cc-8e2f-689ecada2b3b.png)

**Comment by carolabadeer** [comment]
Definitely, thank you for pointing out this issue!

**Comment by carolabadeer** [comment]
Fixed in PR #525
