### ISSUE TITLE
Client doesn't check if middlewareStack is present on client and crashes

### ISSUE THREAD

**Issue by mrjomp** [aws/aws-xray-sdk-node#561]
https://github.com/aws/aws-xray-sdk-node/blob/a9d0cf9cbd0328e40f30554f61b4bd5fac08bafc/packages/core/lib/patchers/aws3_p.ts#L187

**Comment by willarmiros** [comment]
Hi @mrjomp - `middlewareStack` is a required member of the Client object in the AWS SDK's TS definition, do you have a reproduction case of this error?

https://github.com/aws/aws-sdk-js-v3/blob/df1304fa/packages/types/src/client.ts#L32

**Comment by carolabadeer** [comment]
Closing as stale issue - please reopen if there are any further questions
