### ISSUE TITLE
SegmentEmitter module missing a declaration file. 

### ISSUE THREAD

**Issue by ashwini-vaddadi** [aws/aws-xray-sdk-node#576]
I keep getting code: 'MODULE_NOT_FOUND' when trying to build in a container with NODE version 14.19.1. 
I am using the "aws-xray-sdk-core": "^3.2.0" package. On highlighting the warning on VS Code IDE I see the following:

Could not find a declaration file for module 'aws-xray-sdk-core/lib/segment_emitter'. '<PROJECT_PATH>/node_modules/aws-xray-sdk-core/lib/segment_emitter.js' implicitly has an 'any' type.
  If the 'aws-xray-sdk-core' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'aws-xray-sdk-core/lib/segment_emitter';

**Comment by carolabadeer** [comment]
Closing as fix has been merged in PR above
