### ISSUE TITLE
Error: No context available. ns.run() or ns.bind() must be called first.

### ISSUE THREAD

**Issue by NachtmahrEDM** [aws/aws-xray-sdk-node#59]
As XRay currently doesn't support koa, I try to create an instance of the client manually and without a framework-assignment:

```
import * as XRay from 'aws-xray-sdk';
XRay.setLogger(console);
XRay.config([ XRay.plugins.EC2Plugin, XRay.plugins.ECSPlugin ]);
XRay.enableAutomaticMode();
const segment = new XRay.Segment("root");
XRay.setSegment(segment);
```

However this snippet results in an error in this line: `XRay.setSegment(segment);`

Error is: 

> Error: No context available. ns.run() or ns.bind() must be called first.

**Comment by haotianw465** [comment]
Hi, there is a known issue of the incompatibility between Koa and CLS (a core dependency of the X-Ray SDK). The support is in our backlog but we cannot provide a timeline. See more discussion here: https://github.com/aws/aws-xray-sdk-node/issues/4. I'm closing this so we have a central place to trace Koa related issues and progress. Feel free to leave further comments there.

**Comment by NachtmahrEDM** [comment]
But that wasn't really my issue as I try to use AWSXRay independent from any Server-Framework.

**Comment by haotianw465** [comment]
Closing. @NachtmahrEDM feel free to open a new one if you need further assistance to get custom solution working.
