### ISSUE TITLE
Release 3.5.2

### ISSUE THREAD

**Issue by sbstjn** [aws/aws-xray-sdk-node#615]
#614 was merged two days ago but not available at npm yet.

maybe @srprash @jj22ee @carolabadeer just need to dispatch the release pipeline at https://github.com/aws/aws-xray-sdk-node/actions/workflows/release.yml ? 😇

**Comment by srprash** [comment]
Hi @sbstjn 
Apologies for the delay in releasing v3.5.2 to npm. We had some issues and couldn't prioritize the release.

>just need to dispatch the release pipeline

On our end, the release process involves little more than just running the release workflow. 😉 
We are on it now and will have the release done by early next week. Thanks for your patience. 🙂

**Comment by srprash** [comment]
v3.5.2 has been released. Please check it out!
