### ISSUE TITLE
node-fetch not yet supported? 

### ISSUE THREAD

**Issue by kh01** [aws/aws-xray-sdk-node#63]
Hello,

I was under assumption that if I use  "AWSXRay.captureHTTPsGlobal", it would work with all 3rd party http client such as node-fetch. But it seems that it's not the case. Is there a workaround?
It does show the subsegment for the outgoing http call in the xray console, but within the application it's sort of breaking the application since it doesn't return the fetch data.

Error: Failed to get the current sub/segment from the context.
    at Object.contextMissingRuntimeError [as contextMissing] (/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)
    at Object.getSegment (/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)
    at Object.resolveSegment (/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)
    at captureOutgoingHTTPs (/app/node_modules/aws-xray-sdk-core/lib/patchers/http_p.js:67:31)
    at captureHTTPsRequest (/app/node_modules/aws-xray-sdk-core/lib/patchers/http_p.js:152:12)
    at /app/node_modules/node-fetch/lib/index.js:1327:15
    at new WrappedPromise (/app/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at fetch (/app/node_modules/node-fetch/lib/index.js:1319:9)

**Comment by fjsousa** [comment]
@kh01 did you make progress in this issue? I'm facing the same behaviour.

**Comment by kematsuu** [comment]
@kh01 @fjsousa I got same problem. Did you solve it?

**Comment by fjsousa** [comment]
I found that `AWSXRay.captureHTTPsGlobal` seems to be tracing XRay calls, which fails with a context not found error. I passed an environment variable to stop XRay from crashing and log the failed traces instead: `AWS_XRAY_CONTEXT_MISSING=LOG_ERROR`

**Comment by chrisradek** [comment]
@fjsousa 
Have you tried calling `AWSXRay.capturePromise()` somewhere in your code? Since `node-fetch` is a promise-based API, you may need to run the above command once to ensure that context is handled correctly when promises are used.

**Comment by fjsousa** [comment]
Actually using bluebird promises, so doing this instead:
```
const fetch = require('node-fetch');
const clsBluebird = require('cls-bluebird');
clsBluebird(AWSXRAY.getNamespace(), P);
fetch.Promise = P;
```

**Comment by kematsuu** [comment]
In my case, express-session seems to cause the problem. Calling openSegment before express-session, aws-xray-sdk doesn't work. I don't know the reason. Below is the solution.
```
app.use(session());

app.use(AWSXRay.express.openSegment('hoge'));
AWSXRay.captureHTTPsGlobal(require('http'));
```

I can see node-fetch calls api with trace-id just by using captureHTTPsGlobal.

**Comment by mailtokartik1** [comment]
This solution seems to work for me while using `node-fetch`
```var XRay = require('aws-xray-sdk');
var http = XRay.captureHTTPsGlobal(require('http'));
XRay.capturePromise();
const fetch = require('node-fetch')
const segment = new XRay.Segment('A')
var ns = XRay.getNamespace();
ns.enter(ns.createContext()); // Creates new context
XRay.setSegment(segment)
// Middleware function
segment.close()
```
