### ISSUE TITLE
Local Sampling Rules configuration version 1 is not applied

### ISSUE THREAD

**Issue by kvzaytsev** [aws/aws-xray-sdk-node#65]
Hello,

Local Sampling Rules configured with json version 1 do not seem to work anymore.

```
const rules = {
  "rules": [{
    "description": "test.",
    "service_name": "*",
    "http_method": "*",
    "url_path": "*",
    "fixed_target": 0,
    "rate": 1
  }],
  "default": {
    "fixed_target": 1,
    "rate": 0.1
  },
  "version": 1
  }

AWSXRay.middleware.setSamplingRules(rules);
```

Please checkout small example that rules configured with version 1 and withot version 2 are precessed in defferent ways:

https://github.com/kvzaytsev/xray-sampling

I guess that's caused by 

https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/middleware/sampling/local_sampler.js#L131

```
if (config.version === 2)
  params[key] = value;
if (config.version === 1 && key === 'service_name')
  params['host'] = value;
```

if config version is `1`, only `host` field is added to the params object so `httpMethod ` and `urlPath` are not matched using Utils.wildcardMatch.

Thanks!

**Comment by haotianw465** [comment]
Thank you for reporting the issue. We will fix this and roll it out with the recent mysql/pg promise support PRs soon. At the meantime you can use version `2 `and replace key `service_name` with `host` as a workaround. Please note the service sampling rules will have higher precedence over locally defined rules if you have X-Ray daemon `3.x` running and the SDK's pollers manage to get the service sampling rules back, please see this discussion https://github.com/aws/aws-xray-sdk-node/issues/53 for more details.

**Comment by kvzaytsev** [comment]
Awesome! Thanks a lot for the information!
