### ISSUE TITLE
Lots of new logs since 3.7.0

### ISSUE THREAD

**Issue by j0k3r** [aws/aws-xray-sdk-node#656]
Since the 3.7.0 version, we do have a lot of _useless_ logs on all our lambdas:

```
2024-06-06T13:22:09.119Z	undefined	ERROR	_X_AMZN_TRACE_ID is missing required information
2024-06-06T13:22:09.131Z	undefined	ERROR	Empty or non-string trace ID provided
```

3.6.0 doesn't log these messages.

How can we deal with them? How can we silent them or removed them?

**Comment by wangzlei** [comment]
The PR introduced the issue has been reverted by https://github.com/aws/aws-xray-sdk-node/pull/657
Please bump to the latest 3.8.0 with the fix.

**Comment by j0k3r** [comment]
The revert of course fixed the problem.
