### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by Kruspe** [aws/aws-xray-sdk-node#669]
Hey folks,

can we create a new release to get the merged PR released? I am happy to open the PR like #661 to get this on the way.

Or is there something we are waiting on? Maybe a patch release would be enough, but I would have to see what changed since the last release to be sure.

Since I had some time on my hand here is the PR: #670

**Comment by thpierce** [comment]
Thanks for reaching out! We are working on a release now, aiming for end of this week, but may spill over due to workload on our side.
