### ISSUE TITLE
Type safety issue in processTraceData

### ISSUE THREAD

**Issue by kunagpal** [aws/aws-xray-sdk-node#67]
https://github.com/aws/aws-xray-sdk-node/blob/295ed14ec00eb9e6ee51c6098aaad4d56d2b3afe/packages/core/lib/utils.js#L163

In the above function, a header of the form `Root=2134;` (notice the extra semicolon at the end) will cause the function to throw a `TypeError`, as there is no content after the semicolon.

I'm more than happy to send a pull request to add a check for values being present before trimming/splitting them, do let me know what you think.

**Comment by haotianw465** [comment]
You are right. The SDK should be robust on handling malformed or non-standard trace header. A pull request is very welcome

**Comment by kunagpal** [comment]
Hey @haotianw465, glad the pull request got merged. Is there anything I can do to help expedite the release?

**Comment by haotianw465** [comment]
This is fixed as part of `v2.1.0` release. Thank you for your patience.
