### ISSUE TITLE
codecov uploader outdated

### ISSUE THREAD

**Issue by berndfuhrmann** [aws/aws-xray-sdk-node#688]
Currently, the npm package `codecov` is being used in the newest version 3.8.3. This package is deprecated. It might no longer run correctly. At least I had such an issue in one pipeline run: https://github.com/aws/aws-xray-sdk-node/actions/runs/10955762162/job/30600245736?pr=687#step:9:3198

One way of uploading coverage to codecov is described here:
https://docs.codecov.com/docs/codecov-uploader

**Comment by bjrara** [comment]
Thanks for the report. We will fix this deprecation issue, and review the PR!

**Comment by jj22ee** [comment]
Fixed in https://github.com/aws/aws-xray-sdk-node/pull/692
