### ISSUE TITLE
Add support for API Gateway context data?

### ISSUE THREAD

**Issue by kopertop** [aws/aws-xray-sdk-node#8]
I've been trying to find a way to add in support for the API Gateway Context and event data (URL, Path, Headers, etc).

I have a function which should be working to add in the HTTP data to the currently open segment, but this data does not appear to be passed along to XRay:

```javascript
export function initTracking(event: any) {
   const segment = XRay.getSegment();
   if(segment){
      const headers: any = {};
      if(event.headers){
         for(let header_name in event.headers){
            headers[header_name.toLowerCase()] = event.headers[header_name];
         }
      }
      const incoming_request_data = new XRay.middleware.IncomingRequestData({
         url: event.path,
         connection: { 
            encrypted: true,
         },
         headers, 
         method: event.httpMethod,
      });
      segment.addIncomingRequestData(incoming_request_data);
   }
   return segment;
}
```

I also tried creating a new segment, but that also failed (and trying to use XRay.setSegment(segment) caused an error):

```javascript
export function initTracking(event: any) {
   const parent_segment = XRay.getSegment();
   if(parent_segment){
      const segment = new XRay.Segment(parent_segment.name, parent_segment.rootId, parent_segment.id);
      const headers: any = {};
      if(event.headers){
         for(let header_name in event.headers){
            headers[header_name.toLowerCase()] = event.headers[header_name];
         }
      }
      const incoming_request_data = new XRay.middleware.IncomingRequestData({
         url: event.path,
         connection: { 
            encrypted: true,
         },
         headers, 
         method: event.httpMethod,
      });
      segment.addIncomingRequestData(incoming_request_data);
      return segment;
   }
}
```

Is there something I'm missing? Is it possible to have this data automatically picked up by XRay, or if not is there a way to add this into my function so I can add the additional HTTP data available from Lambda when executed from API Gateway?

**Comment by djamison** [comment]
It doesn't look like it's currently possible. The segment you're working with doesn't go anywhere. See [this response](https://forums.aws.amazon.com/thread.jspa?threadID=265808) by @haotianw465.

The best I've been able to do is attach that data to a subsegment. It's not great, but the data is there while drilling down into traces.

```
AWSXRay.captureFunc('incomingRequest', function (subsegment) {
        subsegment.http = new AWSXRay.middleware.IncomingRequestData({
            method: event.httpMethod,
            url: event.path,
            connection: {
                secure: event.headers['CloudFront-Forwarded-Proto'] == 'https'
            },
            headers: {
                'x-forwarded-for': event.headers['X-Forwarded-For'],
                'user-agent': event.headers['User-Agent'],
                host: event.headers['Host']
            }
        });
    });
```

**Comment by kopertop** [comment]
Hmm, that's rather unfortunate. Even adding the http data to a subsegment doesn't make that information appear in the X-Ray console under the "Trace Overview", so I don't think that's a reliable option.

The response by @haotianw465 appears to indicate that the root segment data isn't actually sent to the X-Ray Lambda worker. Is this due to the "Lambda Worker" not being able to accept that data, or is it just because the SDK isn't properly passing that info? i.e. is this something that can be fixed in the SDK?

**Comment by awssandra** [comment]
Hi Kopertop,

The Lambda worker sends it's own segment independent of the SDK, created when the worker spins up and sent when the initialization completes. This is to support active as well as passive tracing for that Lambda function, and capture information regarding failure of the worker to initialize.

What the SDK does is pick up the parent ID and Trace ID of the segment sent by Lambda (they expose this via an environment variable) when the function invokes and creates a 'facade' segment as a placeholder to build subsegments off. This maintains the segment structure as expected by the SDK. Thus, there is no access to the segment to attach additional information as the segment has already been sent to the X-Ray service.

This is more of an issue of integration with other AWS services to improve the API Gateway and Lambda X-Ray experience, which we are continuing to iterate on. Unfortunately there is no great way of handling this at the moment from the SDK side.

**Comment by wparad** [comment]
@kopertop,
It's possible that the information was just delayed to be sent to XRay from Lambda. I've noticed the XRay event emitter is running in the background on lambda, and so sometimes it takes 1 or 2 more calls to the lambda function, have it spin up before the previous execution's data actually is sent there.
