### ISSUE TITLE
Use lodash modules for package dependencies

### ISSUE THREAD

**Issue by chris-feist** [aws/aws-xray-sdk-node#84]
To reduce the bundle size, lodash method modules should be used for package dependencies instead of the whole lodash library. See https://www.npmjs.com/search?q=keywords:lodash-modularized.

Looking at #43, it appears there are only a handful that need to be added.

**Comment by chrisradek** [comment]
@chris-feist 
Thanks for the suggestion. We're happy to consider safe changes that can reduce the size of the SDK. It also looks like we don't have to use lodash for everything we're using it for today, and could possibly just use vanilla JS instead in most cases.

Just curious, when you mention reducing the bundle size, do you mean when using a tool like webpack to create a bundle, or the contents of the node_modules directory?
