### ISSUE TITLE
Remove or optimize engines section

### ISSUE THREAD

**Issue by EugeneDraitsev** [aws/aws-xray-sdk-node#88]
If you will try to run `yarn` with node version >11, f.e. inside docker image node:latest you'll get an error:

```
error aws-xray-sdk@2.1.0: The engine "node" is incompatible with this module. Expected version ">= 4.x <= 10.x". Got "11.6.0"
```
It appears because of engines section in your package.json
```
  "engines": {
    "node": ">= 4.x <= 10.x",
    "npm": ">= 2.x <= 5.x"
}
```

So, question is do you really need node >= 4.x <= 10.x, or maybe you should replace it with >= 4.x and allow users to use aws-xray-sdk-node with latest version of node?

**Comment by haotianw465** [comment]
Hi @EugeneDraitsev, the SDK is only tested under <=10.x and we do have some work need to be done for testing against v11. I'm OK with removing this restriction and have some wording on the `README` about the version we officially support. I will post some update regarding this change as soon as possible.
