### ISSUE TITLE
HapiJS Integration

### ISSUE THREAD

**Issue by moonthug** [aws/aws-xray-sdk-node#94]
I've created a plugin for HapiJS (v17) based on the work you've done for Express. Would you be interested in adding it to your monorepo?

https://github.com/moonthug/hapi-xray

**Comment by chrisradek** [comment]
@moonthug 
Thank you for writing this plugin for Hapi! I'll bring this up with the team internally to discuss.

**Comment by willarmiros** [comment]
Resolving as official support for HapiJS was released in 3.2.0 in the `aws-xray-sdk-hapi` package: https://www.npmjs.com/package/aws-xray-sdk-hapi
