### ISSUE TITLE
xray middleware for micro fails with Error: Failed to get the current sub/segment from the context

### ISSUE THREAD

**Issue by styfle** [aws/aws-xray-sdk-node#95]
I created a repository so you can reproduce the issue here:

https://github.com/styfle/aws-xray-bug

Related to #60

/cc @chrisradek

**Comment by chrisradek** [comment]
@styfle 
Are you seeing this issue everytime you attempt to trace your micro app? One thing I noticed is your package.json uses aws-xray-sdk@2.2.0, but for async support, you'd want to be using aws-xray-sdk@2.1.0-experimental.1

When I ran your example with this change, I was able to see multiple traces when calling the endpoint with GET.

**Comment by styfle** [comment]
@chrisradek Thanks for the response!

I ended up changing the code to use `aws-xray-sdk@2.1.0-experimental.1` but I still needed to access private APIs to get it to log HTTP Request and HTTP Response.

Here's what I ended up with.

```js
const AWSXRay = require('aws-xray-sdk');
const { IncomingRequestData } = AWSXRay.middleware;
console.log('Patching http global');
AWSXRay.captureHTTPsGlobal(require('http'));

function trace(handler) => {
	console.log('start tracing micro');
	return async function traceAsync(req, res) {
		const namespace = AWSXRay.getNamespace();
		const segment = new AWSXRay.Segment('some-segment-name-here');
		segment.http = new IncomingRequestData(req);

		res.on('finish', function finish() {
			console.log('end tracing micro');
			segment.http.close(res);
			segment.http.status = res.statusCode || '';
			if (res.statusCode === 429) {
				segment.throttle = true;
			}
			if (res.headers && res.headers['content-length']) {
				segment.http['content_length'] = res.headers['content-length'];
			}
			segment.close();
		});

		namespace.bindEmitter(req);
		namespace.bindEmitter(res);
		const result = await namespace.runAndReturn(async function run() {
			AWSXRay.setSegment(segment);
			const handlerResponse = await handler(req, res);
			segment.close();
			return handlerResponse;
		});
		return result;
	};
}

function captureAsync(func, args) {
	const { name = 'anonymous' } = func;
	console.log('captureAsync ', name);
	return new Promise((resolve, reject) => {
		AWSXRay.captureAsyncFunc(name, async (subsegment) => {
			try {
				const p = func.apply(this, args);
				let result;
				if (p instanceof Promise) {
					result = await p;
				} else {
					result = p;
				}
				subsegment.close();
				resolve(result);
			} catch (error) {
				subsegment.close(error);
				reject(error);
			}
		});
	});
}

module.exports = { trace, captureAsync };
```

Even with these private APIs, I still sometimes does not log the HTTP Response 🤷‍♂️

**Comment by styfle** [comment]
@chrisradek I think I found another bug.

I can't seem to use an annotation key that contains a hyphen.

For example `segment.addAnnotation('x-now-id', 'abc123')` does not work but `segment.addAnnotation('xNowId', 'abc123')` works as expected.

Is this a known limitation or a bug?

**Comment by chrisradek** [comment]
@styfle 
Annotation [keys](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-segment.html#xray-sdk-nodejs-segment-annotations) can be up to 500 alphanumeric characters. No spaces or symbols except underscores. Values can be up to 1000 unicode characters.

**Comment by styfle** [comment]
I see now.

It was silently dropping that data even with the following flags:

```yml
- AWS_XRAY_DEBUG_MODE=TRUE
- AWS_XRAY_CONTEXT_MISSING=LOG_ERROR
```

I would expect to see some sort of logging error when a segment does not meet this criteria.

**Comment by styfle** [comment]
For some strange reason, there is no response logged around 30% the time (even with my `res.on('finish')` hack above.

![image](https://user-images.githubusercontent.com/229881/52734404-1e815080-2f93-11e9-99e6-ca59d4b66b48.png)

**Comment by styfle** [comment]
@chrisradek  The `experimental` tag does not work with Node 11.

```
error aws-xray-sdk@2.1.0-experimental.1: The engine "node" is incompatible with this module. Expected version ">= 4.x <= 10.x". Got "11.10.0"
```

Is there a reason why the package.json specifies `<= 10.x`?

**Comment by manchuck** [comment]
@styfle  The reason for working on node ``<= 10.x`` is due to the lambda execution environment. Lambada currently executes ``node @ 8.10``

**Comment by chrisradek** [comment]
Closing this since we started talking about multiple issues. If you are still encountering issues after installing the `experimental` tag of the SDK, please feel free to open a new issue.
