### ISSUE TITLE
Lodash vulnerability, upgrade to 4.17.11

### ISSUE THREAD

**Issue by IevgenRagulin** [aws/aws-xray-sdk-node#96]
Please, upgrade lodash to 4.17.11 to fix https://snyk.io/vuln/SNYK-JS-LODASH-73639

I've tried creating a branch, with a fix, but apparently I don't have the permissions:
ERROR: Permission to aws/aws-xray-sdk-node.git denied to IevgenRagulin.
fatal: Could not read from remote repository.

**Comment by IevgenRagulin** [comment]
Thank you for getting back to me @chrisradek . I've realized we can force yarn use a later version of lodash since the version in aws-xray-sdk is specified as **^**4.7.10

**Comment by chrisradek** [comment]
@IevgenRagulin 
Yes, NPM should also allow you to specify a newer version as long as it's version 4.x. We'll still make the update to force users off of 4.17.10 in the future.

**Comment by chrisradek** [comment]
This can be closed as we've updated the lower bound.
